import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,change,summary} from '../server/model.mjs';
const day='2026-09-19';
function fixture(){let b=fresh();for(const a of [{name:'Checking',kind:'cash',openingBalance:1000},{name:'Family',kind:'loan',debtType:'personal',openingBalance:500,payment:100,dueDate:day}])b=change(b,'account',{...a,balanceDate:day,frequency:'Monthly'},day);b=change(b,'transaction',{name:'VENMO',accountId:b.accounts[0].id,date:day,amount:100,direction:'Outflow',category:'Other',historical:true},day);b.transactions[0].plaidTransactionId='bank-tx';return b;}
const apply=(b,p={})=>change(b,'applyPersonalDebt',{transactionId:b.transactions[0].id,debtId:b.accounts[1].id,principal:90,balanceTreatment:'reduce',...p},day);
test('imported Venmo links once, reduces principal, completes schedule and never deducts cash',()=>{const b=fixture(),before=JSON.stringify(b),key=b.accounts[1].id+'@'+day,c=apply(b,{occurrenceKey:key}),s=summary(c,day);assert.equal(s.accounts[0].balance,1000);assert.equal(s.accounts[1].balance,410);assert.equal(c.transactions[0].historical,true);assert.equal(c.transactions[0].category,'Debt payment');assert.equal(c.payments[0].amount,100);assert.equal(c.payments[0].principal,90);assert.ok(!s.upcoming.some(e=>e.key===key));assert.throws(()=>apply(c),/unlinked/);assert.equal(JSON.stringify(b),before);const removed=change(c,'remove',{list:'payments',id:c.payments[0].id},day);assert.equal(summary(removed,day).accounts[1].balance,500);assert.equal(summary(removed,day).accounts[0].balance,1000);assert.equal(removed.transactions[0].category,'Other');});
test('history already included leaves both balances unchanged and retains payment history',()=>{let b=fixture();b.transactions[0].date='2026-08-01';assert.throws(()=>apply(b),/predates/);const c=apply(b,{balanceTreatment:'included'});assert.equal(summary(c,day).accounts[1].balance,500);assert.equal(summary(c,day).accounts[0].balance,1000);assert.equal(c.payments[0].balanceIncluded,true);const d=change(c,'remove',{list:'payments',id:c.payments[0].id},day);assert.equal(summary(d,day).accounts[1].balance,500);});
test('existing payment link does not reduce principal again and removes duplicate cash deduction',()=>{let b=fixture();b=change(b,'payment',{debtId:b.accounts[1].id,fundingId:b.accounts[0].id,amount:100,principal:80,date:day},day);assert.throws(()=>apply(b),/similar debt payment/);const c=apply(b,{existingPaymentId:b.payments[0].id});assert.equal(c.payments.length,1);assert.equal(c.payments[0].principal,80);assert.equal(summary(c,day).accounts[1].balance,420);assert.equal(summary(c,day).accounts[0].balance,1000);});
test('invalid principal, linked or non-cash activity and wrong schedule are rejected atomically',()=>{for(const flag of ['pending','excluded','adjustment','bankMatchId','goalId']){const b=fixture();b.transactions[0][flag]=true;assert.throws(()=>apply(b),/unlinked/);}const b=fixture(),before=JSON.stringify(b);assert.throws(()=>apply(b,{principal:101}),/Principal/);assert.throws(()=>apply(b,{occurrenceKey:'wrong@'+day}),/scheduled/);assert.throws(()=>apply(b,{debtId:b.accounts[0].id}),/personal debt/);assert.equal(JSON.stringify(b),before);});
test('ordinary cash outflow remains deducted once after linking',()=>{const b=fixture();b.transactions[0].historical=false;const c=apply(b);assert.equal(summary(c,day).accounts[0].balance,900);assert.equal(summary(c,day).accounts[1].balance,410);});
