import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,change,summary,balances,incomeEvents} from '../server/model.mjs';
import {wishesPausedForBuffer} from '../analysis.js';
import {attentionItems} from '../workflow.js';
const day='2026-09-15';
function base(){let b=fresh();b=change(b,'account',{name:'Checking',kind:'cash',openingBalance:2000,balanceDate:'2026-09-01'},day);return change(b,'settings',{buffer:400,planningConfirmed:true},day);}
test('Safe to Spend reserves the next seven days without counting future income as cash',()=>{let b=base();b=change(b,'income',{name:'Work',amount:500,date:'2026-09-29',frequency:'Biweekly'},day);b=change(b,'bill',{name:'Internet',amount:60,date:'2026-09-20',frequency:'One-time'},day);b=change(b,'bill',{name:'Rent',amount:600,date:'2026-09-25',frequency:'Monthly'},day);b=change(b,'bill',{name:'Car insurance',amount:250,date:'2026-10-20',frequency:'Monthly'},day);const before=summary(b,day);b=change(b,'forecastPreferences',{billProtection:'payday',forecastIncome:'expected'},day);const after=summary(b,day);assert.equal(after.cash.safeToSpend,before.cash.safeToSpend);assert.equal(before.cash.safeToSpend,1540);assert.equal(after.cash.balance,2000);assert.equal(after.protectionEnd,'2026-09-21');assert.equal(after.weekBills.length,1);assert.equal(after.protectedBills.length,1);});
test('default bill protection stays at seven days when no paycheck is expected',()=>{let b=base();b=change(b,'bill',{name:'Rent',amount:600,date:'2026-09-20',frequency:'One-time'},day);b=change(b,'bill',{name:'Car insurance',amount:250,date:'2026-10-20',frequency:'One-time'},day);const s=summary(b,day);assert.equal(s.protectionEnd,'2026-09-21');assert.equal(s.protectedBills.length,1);assert.equal(s.cash.safeToSpend,1000);});
test('overdue reserve appears once and skipping releases it without changing balances',()=>{let b=base();b=change(b,'bill',{name:'Old bill',amount:60,date:'2026-09-10',frequency:'One-time'},day);b=change(b,'overduePreferences',{overdueMode:'reserve',overdueSince:'2026-09-01'},day);let s=summary(b,day);assert.equal(s.overdue.length,1);assert.equal(s.plan.forecast[0].cash,1940);assert.equal(s.cash.safeToSpend,1540);b=change(b,'occurrence',{key:b.bills[0].id+'@2026-09-10',date:'2026-09-10',status:'Skipped'},day);s=summary(b,day);assert.equal(s.overdue.length,0);assert.equal(s.cash.safeToSpend,1600);assert.equal(s.cash.balance,2000);});
test('paid overdue bill replaces reserve with actual cash once',()=>{let b=base();b=change(b,'bill',{name:'Old bill',amount:60,date:'2026-09-10',frequency:'One-time'},day);b.settings.overdueMode='reserve';b.settings.overdueSince='2026-09-01';const before=summary(b,day);b=change(b,'occurrence',{key:b.bills[0].id+'@2026-09-10',date:'2026-09-10',status:'Paid',accountId:b.accounts[0].id},day);const after=summary(b,day);assert.equal(after.cash.safeToSpend,before.cash.safeToSpend);assert.equal(after.overdue.length,0);assert.equal(after.cash.balance,1940);});
test('legacy income policy cannot exclude a source or change recorded pay',()=>{let b=base();b=change(b,'incomeProfile',{name:'Work',amount:500,date:day,frequency:'Weekly',estimateMode:'average'},day);b=change(b,'transaction',{name:'Work',amount:500,date:'2026-09-14',direction:'Inflow',category:'Income',accountId:b.accounts[0].id},day);const cash=balances(b,day)[0].balance;b.settings.forecastIncome='manual';assert.ok(incomeEvents(b,day,'2026-10-15',day).length);b.settings.forecastIncome='cautious';assert.ok(incomeEvents(b,day,'2026-10-15',day).length);assert.equal(balances(b,day)[0].balance,cash);b=change(b,'forecastPreferences',{forecastIncome:'manual'},day);assert.equal(b.settings.forecastIncome,undefined);});
test('wish pause switch preserves reserved savings and individually saved records',()=>{let b=base();b.settings.buffer=2500;b.wishes=[{id:'w',cost:300,saved:100,style:'Automatic'}];assert.equal(wishesPausedForBuffer(summary(b,day)),false);b=change(b,'wishProtection',{pauseWishesBelowBuffer:false},day);assert.equal(wishesPausedForBuffer(summary(b,day)),false);assert.equal(summary(b,day).protectedSavings,100);});
test('category review retains suggestions and transfer semantics without balance effects',()=>{let b=base();b=change(b,'importPreferences',{reviewImportedCategories:true},day);b.reviewTransactions=[{id:'a',name:'Store',amount:30,date:day,accountId:b.accounts[0].id,direction:'Outflow',category:'Shopping'},{id:'t',name:'Transfer',amount:40,date:day,accountId:b.accounts[0].id,direction:'Outflow',category:'Transfer'}];b=change(b,'reviewHistory',{ids:['a','t'],accept:true},day);assert.equal(b.transactions[0].category,'Other');assert.equal(b.transactions[0].suggestedCategory,'Shopping');assert.equal(b.transactions[1].category,'Transfer');assert.equal(summary(b,day).cash.balance,2000);b=change(b,'category',{id:'a',category:'Shopping'},day);assert.equal(b.transactions[0].suggestedCategory,undefined);});
test('invalid policies are rejected without changing original budget',()=>{const b=base();assert.equal(change(b,'forecastPreferences',{billProtection:'x',forecastIncome:'expected'},day).settings.forecastIncome,undefined);assert.throws(()=>change(b,'wishProtection',{pauseWishesBelowBuffer:'true'},day));assert.throws(()=>change(b,'overduePreferences',{overdueMode:'reserve',overdueSince:'2026-10-01'},day));assert.equal(b.settings.overdueMode,undefined);});
test('legacy bill protection preferences cannot change the automatic seven-day window',()=>{let b=base();b=change(b,'income',{name:'Work',amount:500,date:'2026-09-29',frequency:'Biweekly'},day);b=change(b,'bill',{name:'Rent',amount:600,date:'2026-09-20',frequency:'One-time'},day);b=change(b,'bill',{name:'Car insurance',amount:250,date:'2026-10-20',frequency:'One-time'},day);b.settings.billProtection='payday';const s=summary(b,day);assert.equal(s.protectionEnd,'2026-09-21');assert.equal(s.protectedBills.length,1);assert.equal(s.cash.safeToSpend,1000);b=change(b,'forecastPreferences',{forecastIncome:'expected'},day);assert.equal(b.settings.billProtection,'payday');assert.equal(summary(b,day).cash.safeToSpend,1000);});
test('buffer warnings are automatic even when a legacy alert preference is off',()=>{let b=base();b.settings.alerts=false;const s=summary(b,day);s.cash.minimumCash=s.cash.bufferTarget-1;assert.ok(attentionItems(b,s).some(item=>item.key==='buffer'));});
