import test from 'node:test';import assert from 'node:assert/strict';import {fresh,change,summary,balances} from '../server/model.mjs';import {attentionItems,reviewState,reviewWarningItems} from '../workflow.js';
const day='2026-09-15';
function seed(){let b=fresh();b=change(b,'account',{name:'Checking',kind:'cash',openingBalance:2000,balanceDate:day},day);b=change(b,'settings',{buffer:400,planningConfirmed:true},day);return b;}
test('same-amount Home confirmation clears pending review and survives reload',()=>{let b=seed();b.accounts[0].verified=false;b=change(b,'confirmBalance',{id:b.accounts[0].id,balance:2000},day);b=JSON.parse(JSON.stringify(b));assert.equal(reviewState(b).balances.length,0);assert.equal(b.transactions.length,0);assert.equal(b.accounts[0].confirmedAt,day);assert.equal(summary(b,day).ready,true);});
test('corrected Home confirmation updates current cash once',()=>{let b=seed();b.accounts[0].verified=false;b=change(b,'confirmBalance',{id:b.accounts[0].id,balance:2150},day);assert.equal(balances(b,day)[0].balance,2150);assert.equal(b.transactions[0].amount,150);b=change(b,'confirmBalance',{id:b.accounts[0].id,balance:2150},day);assert.equal(b.transactions.length,1);assert.equal(reviewState(b).balances.length,0);});
test('review warning dismissal persists and new Other records bring it back',()=>{let b=seed();for(const name of ['A','B'])b=change(b,'transaction',{name,amount:5,date:day,direction:'Outflow',accountId:b.accounts[0].id},day);assert.ok(!attentionItems(b,summary(b,day)).some(x=>['uncategorized','records'].includes(x.key)));assert.equal(reviewWarningItems(b).find(x=>x.kind==='other').pending.length,2);b=change(b,'dismissReviewWarning',{kind:'other'},day);b=JSON.parse(JSON.stringify(b));assert.ok(!reviewWarningItems(b).some(x=>x.kind==='other'));assert.equal(reviewState(b).uncategorized.length,2);b=change(b,'transaction',{name:'New',amount:6,date:day,direction:'Outflow',accountId:b.accounts[0].id},day);assert.equal(reviewWarningItems(b).find(x=>x.kind==='other').pending.length,1);});
test('completed work removes its attention block without a click',()=>{let b=seed();b.accounts[0].verified=false;assert.ok(attentionItems(b,summary(b,day)).some(x=>x.key==='accounts'));b=change(b,'confirmBalance',{id:b.accounts[0].id,balance:2000},day);assert.ok(!attentionItems(b,summary(b,day)).some(x=>x.key==='accounts'));b=change(b,'checkin',{balancesReviewed:true,billsReviewed:true,incomeReviewed:true,schedule:'same'},day);assert.equal(attentionItems(b,summary(b,day)).length,0);});
test('deleted recurring expense can be restored after other edits without losing skipped status',()=>{let b=seed();b=change(b,'bill',{name:'Internet',amount:60,date:day,frequency:'Monthly',category:'Utilities'},day);const id=b.bills[0].id;b=change(b,'occurrence',{key:id+'@'+day,date:day,status:'Skipped'},day);b=change(b,'remove',{list:'bills',id},day);assert.equal(b.bills.length,0);b=change(b,'need',{name:'Shoes',cost:40,urgency:'High'},day);b=JSON.parse(JSON.stringify(b));b=change(b,'restoreBill',{id},day);assert.equal(b.bills[0].category,'Utilities');assert.equal(b.deletedBills.length,0);assert.equal(b.needs.length,1);assert.equal(b.overrides[id+'@'+day].status,'Skipped');assert.throws(()=>change(b,'restoreBill',{id},day));});
test('permanent deletion removes only the selected archived bill and its overrides',()=>{let b=seed();b=change(b,'bill',{name:'Internet',amount:60,date:day,frequency:'Monthly'},day);const id=b.bills[0].id;b=change(b,'occurrence',{key:id+'@'+day,date:day,status:'Skipped'},day);b=change(b,'remove',{list:'bills',id},day);b=change(b,'purgeBill',{id},day);assert.equal(b.deletedBills.length,0);assert.equal(b.overrides[id+'@'+day],undefined);assert.equal(b.accounts.length,1);assert.throws(()=>change(b,'restoreBill',{id},day));});
