import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {spawn} from 'node:child_process';import {once} from 'node:events';import {scryptSync} from 'node:crypto';
test('real HTTP server: private sign-in, saved changes, imports, static protections and no external service',{timeout:20000},async()=>{
 const dir=await mkdtemp(join(tmpdir(),'budget-independent-http-')),config=join(dir,'BudgetHQ');await mkdir(config);const salt='isolated-test-salt',password='test-only-long-password';await writeFile(join(config,'owner.json'),JSON.stringify({salt,hash:scryptSync(password,salt,64).toString('hex')}));
 // Instrument outbound HTTP/HTTPS to fail if the independent server tries a bank
 // or spreadsheet call. Browser-side fetch is separately restricted by CSP.
 const guard=join(dir,'network-guard.mjs');await writeFile(guard,`import http from 'node:http';import https from 'node:https';const blocked=()=>{throw Error('OUTBOUND_NETWORK_NOT_ALLOWED')};http.request=blocked;https.request=blocked;http.get=blocked;https.get=blocked;globalThis.fetch=blocked;`);
 const child=spawn(process.execPath,['--import',guard,'server/server.mjs'],{cwd:new URL('..',import.meta.url),env:{...process.env,BUDGET_HQ_DATA_HOME:dir},stdio:['ignore','pipe','pipe']});let stderr='';child.stderr.on('data',b=>stderr+=b);
 try{await new Promise((resolve,reject)=>{child.stdout.on('data',b=>{if(String(b).includes('Budget HQ Independent:'))resolve();});child.once('exit',()=>reject(Error(stderr)));child.once('error',reject);});
 const request=(path,options={})=>fetch('http://127.0.0.1:4173'+path,{redirect:'manual',...options});assert.equal((await request('/')).status,303);assert.equal((await request('/api/budget')).status,401);const publicPalette=await request('/palette.css');assert.equal(publicPalette.status,200);assert.match(publicPalette.headers.get('content-type'),/text\/css/);
 const login=await request('/api/owner/login',{method:'POST',headers:{'X-Budget-HQ':'1','Content-Type':'application/json'},body:JSON.stringify({password})});assert.equal(login.status,200);const Cookie=login.headers.get('set-cookie').split(';')[0],headers={Cookie,'X-Budget-HQ':'1','Content-Type':'application/json'},get=path=>request(path,{headers}),post=(path,body)=>request(path,{method:'POST',headers,body:JSON.stringify(body)});
 const response=await get('/api/budget');assert.equal(response.status,200);const data=await response.json();assert.equal(data.book.accounts.length,0);assert.equal(data.summary.ready,false);for(const list of ['bills','incomes','transactions','payments','needs','wishes','goals','sinking','reviewTransactions'])assert.equal(data.book[list].length,0,list);assert.equal(data.book.settings.buffer,0);
 const saved=await post('/api/write',{revision:data.book.revision,operationId:'http-write',action:'decision',data:{name:'HTTP test',notes:'Saved without external services'}});assert.equal(saved.status,200);assert.equal((await saved.json()).book.decisions[0].name,'HTTP test');
 const bank=await get('/api/plaid/status');assert.equal(bank.status,200);const bankState=await bank.json();assert.equal(bankState.importsPaused,false);assert.equal(bankState.configured,false);assert.deepEqual(bankState.items,[]);
 assert.equal((await request('/api/plaid/status')).status,401);
 assert.equal((await request('/api/plaid/configure',{method:'POST',headers:{...headers,Origin:'https://other.example'},body:'{}'})).status,403);
 assert.equal((await post('/api/plaid/start',{})).status,400);
 const beforeBank=await (await get('/api/export')).json();
 const mail=await post('/api/mail/configure',{host:'smtp.example.com',from:'owner@example.com',user:'owner@example.com',password:'test-only-secret'});assert.equal(mail.status,200);assert.ok(!(await mail.text()).includes('test-only-secret'));assert.equal((await (await get('/api/mail/status')).json()).configured,true);assert.deepEqual(await (await get('/api/export')).json(),beforeBank);
 const configured=await post('/api/plaid/configure',{clientId:'fake-test-client',secret:'fake-test-secret',environment:'sandbox'});assert.equal(configured.status,200);assert.ok(!(await configured.text()).includes('fake-test-secret'));
 assert.deepEqual(await (await get('/api/export')).json(),beforeBank);
 const home=await get('/');assert.equal(home.status,200);const html=await home.text();assert.match(html,/src="\/design-editor\.js"/);assert.match(html,/href="\/design-editor\.css"/);assert.match(home.headers.get('content-security-policy'),/connect-src 'self'/);const app=await (await get('/app.js')).text();for(const m of app.matchAll(/^import .*?from ['"]\.\/([^'"]+)['"]/gm))assert.equal((await get('/'+m[1])).status,200);
 for(const path of ['/styles.css','/mobile.css','/refined-expenses.css','/desktop-theme.css','/refinements.css','/tools.css','/palette.css','/refinement-082.css','/refinement-083.css','/refinement-085.css','/refinement-086.css']){const asset=await get(path);assert.equal(asset.status,200,path);assert.match(asset.headers.get('content-type'),/text\/css/);}
 for(const path of ['/tools-ui.js','/tools-data.js','/need-matches.js','/icon-catalog.js','/design-editor.js','/design-render.js','/design-schema.js','/design-styles.js','/design-elements.js']){const asset=await get(path);assert.equal(asset.status,200);assert.match(asset.headers.get('content-type'),/javascript/);}
 for(const path of ['/server/config.mjs','/migration/source.json','/api/google/summary','/api/plaid/sync'])assert.equal((await get(path)).status,404,path);
 assert.equal((await request('/api/write',{method:'POST',headers:{...headers,Origin:'https://other.example'},body:'{}'})).status,403);
 const cal=await (await get('/api/calendar?start=2026-10-01&end=2026-10-31')).json();assert.ok(Array.isArray(cal.events));assert.equal((await get('/api/calendar?start=bad&end=bad')).status,400);
 assert.equal((await post('/api/backup',{})).status,200);const history=await (await get('/api/history')).json();assert.ok(history.backups.length>=2);assert.equal((await get('/api/export')).status,200);
 assert.equal((await post('/api/owner/logout',{})).status,200);assert.equal((await get('/api/budget')).status,401);assert.ok(!stderr.includes('OUTBOUND_NETWORK_NOT_ALLOWED'));
 }finally{const exited=child.exitCode!==null?Promise.resolve():once(child,'exit');child.kill('SIGTERM');await exited;await rm(dir,{recursive:true,force:true});}
});
