import test from 'node:test';
import assert from 'node:assert/strict';
import {recurringIncomeSuggestions,recurringBillSuggestions} from '../analysis.js';
import {fresh,change,summary,incomeEvents} from '../server/model.mjs';
const day='2026-09-18';
function fixture(){const b=fresh();b.accounts=[{id:'cash',name:'Checking',kind:'cash',openingBalance:2000,balanceDate:'2026-01-01',verified:true}];b.transactions=['2026-08-20','2026-09-03','2026-09-17'].map((date,i)=>({id:'deposit'+i,accountId:'cash',name:'Employer Payroll',direction:'Inflow',date,amount:[950,1000,1800][i],category:'Income',historical:true}));return b;}
test('suggest income using reviewed deposits and median take-home, never a bill',()=>{const b=fixture(),before=JSON.stringify(b),[s]=recurringIncomeSuggestions(b,day);assert.equal(s.frequency,'Biweekly');assert.equal(s.next,'2026-10-01');assert.equal(s.amount,1000);assert.equal(s.latest,1800);assert.equal(s.variable,true);assert.equal(s.evidence.length,3);assert.equal(recurringBillSuggestions(b,day).length,0);assert.equal(JSON.stringify(b),before);});
test('refunds, transfers, corrections, pending, ambiguous categories and debt accounts are excluded',()=>{for(const extra of [{name:'Employer Refund'},{name:'Bank Transfer'},{toAccountId:'other'},{adjustment:true},{pending:true},{category:'Other'},{direction:'Outflow'},{excluded:true},{paymentId:'p'}]){const b=fixture();b.transactions.forEach(t=>Object.assign(t,extra));assert.equal(recurringIncomeSuggestions(b,day).length,0,JSON.stringify(extra));}const b=fixture();b.accounts[0].kind='credit';assert.equal(recurringIncomeSuggestions(b,day).length,0);});
test('insufficient, irregular, split-account and duplicate history cannot create suggestions',()=>{const b=fixture();b.transactions.pop();assert.equal(recurringIncomeSuggestions(b,day).length,0);const c=fixture();c.transactions[1].date='2026-08-22';assert.equal(recurringIncomeSuggestions(c,day).length,0);const d=fixture();d.accounts.push({...d.accounts[0],id:'second'});d.transactions[0].accountId='second';assert.equal(recurringIncomeSuggestions(d,day).length,0);const e=fixture();e.transactions.push({...e.transactions[0],id:'dupe'});assert.equal(recurringIncomeSuggestions(e,day).length,0);});
test('accepted source produces one future paycheck schedule and no added balance or history',()=>{let b=fixture();const [s]=recurringIncomeSuggestions(b,day),before=summary(b,day).cash.balance,p={key:s.key,mode:'accept',name:'My Job',amount:900,frequency:'Biweekly',date:s.next};b=change(b,'incomeSuggestion',p,day);assert.equal(b.incomes.length,1);assert.equal(b.incomes[0].historyName,'Employer Payroll');assert.equal(b.incomes[0].amount,900);assert.equal(b.incomes[0].accountId,'cash');assert.equal(summary(b,day).cash.balance,before);assert.deepEqual(b.transactions,fixture().transactions);assert.equal(incomeEvents(b,'2026-10-01','2026-10-01',day)[0].amount,900);assert.equal(recurringIncomeSuggestions(b,day).length,0);assert.throws(()=>change(b,'incomeSuggestion',p,day),/already/);});
test('existing source names and edited-name collisions prevent duplicate sources',()=>{const b=fixture();b.incomes=[{name:'Employer-Payroll',frequency:'Biweekly',active:true}];assert.equal(recurringIncomeSuggestions(b,day).length,0);b.incomes=[{name:'My Job',frequency:'Monthly',active:true}];const [s]=recurringIncomeSuggestions(b,day);assert.throws(()=>change(b,'incomeSuggestion',{key:s.key,mode:'accept',name:'My Job',amount:1000,date:s.next,frequency:s.frequency},day),/already exists/);});
test('dismiss and restore are independent of bills; dates and amounts validated',()=>{let b=fixture();const [s]=recurringIncomeSuggestions(b,day);b=change(b,'incomeSuggestion',{key:s.key,mode:'dismiss'},day);assert.equal(recurringIncomeSuggestions(b,day)[0].dismissed,true);assert.equal(b.dismissedRecurring,undefined);b=change(b,'incomeSuggestion',{key:s.key,mode:'restore'},day);assert.equal(recurringIncomeSuggestions(b,day)[0].dismissed,false);for(const extra of [{amount:0},{date:'2026-08-01'},{frequency:'One-time'},{date:'invalid'}])assert.throws(()=>change(b,'incomeSuggestion',{key:s.key,mode:'accept',name:s.name,amount:1000,date:s.next,frequency:s.frequency,...extra},day));});

test('Alamo employer deposits repair old categories and group payroll descriptions into one source',async()=>{
 const {classifyTransaction,categorizeOther}=await import('../categories.js');const {incomeEstimate}=await import('../analysis.js');
 const b=fixture();b.transactions.forEach((t,i)=>{t.name=['ALAMO DRAFTHOUSE','ACH ALAMO DRAFT HOUSE PAYROLL 0903','Alamo Drafthouse Cinema DIR DEP'][i];t.category='Entertainment';t.bankCategory={primary:'ENTERTAINMENT'};});
 assert.equal(categorizeOther(b),3);assert.ok(b.transactions.every(t=>t.category==='Income'));const [s]=recurringIncomeSuggestions(b,day);assert.equal(s.name,'Alamo Drafthouse');assert.equal(s.frequency,'Biweekly');assert.equal(s.evidence.length,3);assert.equal(incomeEstimate(b,{name:s.name},day).matchedCount,3);assert.equal(incomeEstimate(b,{name:s.name},day).count,2);
 assert.equal(classifyTransaction({name:'Alamo Drafthouse',direction:'Outflow'}),'Entertainment');for(const name of ['ALAMO DRAFTHOUSE REFUND','ALAMO DRAFTHOUSE REVERSAL','ALAMO DRAFTHOUSE REIMBURSEMENT'])assert.notEqual(classifyTransaction({name,direction:'Inflow'}),'Income');
 b.transactions[0].category='Other';b.transactions[0].categoryConfirmed=true;assert.equal(categorizeOther(b),0);assert.equal(b.transactions[0].category,'Other');
 b.incomes=[{name:'Alamo Drafthouse',active:true}];assert.equal(recurringIncomeSuggestions(b,day).length,0);
});

test('reported Alamo dates suggest weekly income with explicit gap review, without altering history',()=>{
 const b=fixture();b.transactions.forEach((t,i)=>{t.name='Alamo Drafthouse';t.date=['2026-08-27','2026-09-03','2026-09-17'][i];});
 const before=JSON.stringify(b),[s]=recurringIncomeSuggestions(b,'2026-09-19');
 assert.equal(s.frequency,'Weekly');assert.equal(s.cadenceNeedsReview,true);assert.equal(s.next,'2026-09-24');assert.equal(s.evidence.length,3);assert.equal(JSON.stringify(b),before);
 const next=change(b,'incomeSuggestion',{key:s.key,mode:'accept',name:s.name,amount:900,frequency:'Biweekly',date:'2026-10-01'},'2026-09-19');assert.equal(next.incomes[0].frequency,'Biweekly');assert.deepEqual(next.transactions,b.transactions);
 const bills=structuredClone(b);bills.transactions.forEach(t=>{t.direction='Outflow';t.category='Entertainment';});assert.equal(recurringBillSuggestions(bills,'2026-09-19').length,0);
});
test('gap detection retains regular biweekly and rejects very long gaps',()=>{
 const b=fixture();assert.equal(recurringIncomeSuggestions(b,day)[0].frequency,'Biweekly');assert.equal(recurringIncomeSuggestions(b,day)[0].cadenceNeedsReview,false);
 b.transactions.forEach((t,i)=>t.date=['2026-08-01','2026-08-08','2026-09-17'][i]);assert.equal(recurringIncomeSuggestions(b,day).length,0);
});
