import test from 'node:test';import assert from 'node:assert/strict';import {generateKeyPairSync,sign,createHash} from 'node:crypto';import {PlaidWebhooks,webhookURL} from '../server/plaid-webhooks.mjs';
const now=Date.now(),{publicKey,privateKey}=generateKeyPairSync('ec',{namedCurve:'P-256'}),key={...publicKey.export({format:'jwk'}),kid:'key',alg:'ES256',expired_at:null};
function signed(raw,override={}){const h=Buffer.from(JSON.stringify({alg:'ES256',kid:'key'})).toString('base64url'),p=Buffer.from(JSON.stringify({iat:Math.floor(now/1000),request_body_sha256:createHash('sha256').update(raw).digest('hex'),...override})).toString('base64url');return h+'.'+p+'.'+sign('sha256',Buffer.from(h+'.'+p),{key:privateKey,dsaEncoding:'ieee-p1363'}).toString('base64url');}
function fixture(){const data=new Map(),calls=[];const store={get:async(k,d)=>structuredClone(data.get(k)??d),put:async(k,v)=>data.set(k,structuredClone(v))};return {data,calls,h:new PlaidWebhooks({store,getKey:async()=>key,knownItem:async id=>id==='bank',refresh:async id=>calls.push(id),now:()=>now})};}
const raw=Buffer.from(JSON.stringify({item_id:'bank',webhook_type:'TRANSACTIONS',webhook_code:'SYNC_UPDATES_AVAILABLE'}));
test('signed notifications durably coalesce and only refresh their bank',async()=>{const {h,data,calls}=fixture();await h.accept(raw,signed(raw));await h.accept(raw,signed(raw));assert.equal(data.get('webhook-queue').length,1);await h.tick();assert.deepEqual(calls,['bank']);assert.equal(data.get('webhook-queue').length,0);});
test('bad signature, changed body and expired token never queue',async()=>{const {h,data}=fixture();await assert.rejects(h.accept(Buffer.from('{}'),signed(raw)));await assert.rejects(h.accept(raw,signed(raw,{iat:Math.floor(now/1000)-301})));const token=signed(raw);await assert.rejects(h.accept(raw,token.slice(0,-10)+'aaaaaaaaaa'));assert.equal(data.size,0);});
test('failed updates persist for retry and unsupported notifications do nothing',async()=>{const {h,data}=fixture();h.refresh=async()=>{throw Error('offline');};await h.accept(raw,signed(raw));await h.tick();assert.equal(data.get('webhook-queue')[0].attempts,1);assert.ok(data.get('webhook-queue')[0].next>now);const other=Buffer.from(JSON.stringify({item_id:'unknown',webhook_type:'TRANSACTIONS',webhook_code:'SYNC_UPDATES_AVAILABLE'}));assert.equal((await h.accept(other,signed(other))).ignored,true);});
test('receiver configuration requires exact HTTPS callback without credentials',()=>{assert.equal(webhookURL(''),'');assert.throws(()=>webhookURL('http://example.com/plaid/webhook'));assert.throws(()=>webhookURL('https://u:p@example.com/plaid/webhook'));assert.throws(()=>webhookURL('https://example.com/'));assert.equal(webhookURL('https://example.com/plaid/webhook'),'https://example.com/plaid/webhook');});
