import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,readFile} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {PrivateStore} from '../server/private-store.mjs';import {BudgetService} from '../server/service.mjs';import {fresh} from '../server/model.mjs';
async function fixture(t){const dir=await mkdtemp(join(tmpdir(),'budget-test-'));t.after(()=>rm(dir,{recursive:true,force:true}));const store=new PrivateStore(dir),s=await new BudgetService(store,async()=>fresh()).init();return {dir,store,s};}
const update=(s,id='one',buffer=123)=>({revision:s.read().book.revision,operationId:id,action:'settings',data:{buffer,planningConfirmed:true}});
test('atomic encrypted writes survive restart and retry is idempotent',async t=>{const {s,store,dir}=await fixture(t),request=update(s);await s.write(request);const repeated=await s.write(request);assert.equal(repeated.repeated,true);assert.equal(s.history().length,1);assert.ok(!(await readFile(join(dir,'budget.enc'),'utf8')).includes('planningConfirmed'));const restarted=await new BudgetService(store,()=>{throw Error('must not reseed');}).init();assert.equal(restarted.read().book.settings.buffer,123);});
test('concurrent conflicting tabs cannot overwrite a later change',async t=>{const {s}=await fixture(t);const a=update(s,'a'),b=update(s,'b');const r=await Promise.allSettled([s.write(a),s.write(b)]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.match(r.find(x=>x.status==='rejected').reason.message,/another tab/);});
test('undo preview restores previous value and refuses stale recovery',async t=>{const {s}=await fixture(t);await s.write(update(s));const preview=await s.preview({kind:'undo',id:s.history()[0].id});await s.write(update(s,'two',222));await assert.rejects(s.restore({token:preview.token}),/changed since preview/);const next=await s.preview({kind:'undo',id:s.history()[0].id});await s.restore({token:next.token});assert.equal(s.read().book.settings.buffer,123);});
test('backup restore previews original contents and saves pre-restore backup',async t=>{const {s}=await fixture(t);const backup=await s.backup();await s.write(update(s));const preview=await s.preview({kind:'backup',id:backup.id});assert.equal(preview.accounts,0);await s.restore({token:preview.token});assert.equal(s.read().book.settings.buffer,400);assert.ok((await s.backups()).some(n=>n.startsWith('backup-before-restore')));});
test('failed persistence leaves in-memory state untouched',async t=>{const {s,store}=await fixture(t),before=s.read().book.revision;store.put=async()=>{throw Error('disk full');};await assert.rejects(s.write(update(s)),/disk full/);assert.equal(s.read().book.revision,before);assert.equal(s.history().length,0);});
test('contextual Undo is bound to its own write and cannot undo a newer change',async t=>{const {s}=await fixture(t);const first=await s.write(update(s,'first'));assert.ok(first.undoId);await s.write(update(s,'second',222));await assert.rejects(s.preview({kind:'undo',id:first.undoId}),/latest change/);const second=s.read(),p=await s.preview({kind:'undo',id:second.undoId});await s.restore({token:p.token});assert.equal(s.read().book.settings.buffer,123);});
test('snapshot failure does not report a committed ledger edit as failed',async t=>{const {s,store}=await fixture(t),put=store.put.bind(store);store.put=async(name,value)=>{if(name.startsWith('monthly-'))throw Error('snapshot failed');return put(name,value);};const d=await s.write(update(s));assert.equal(d.book.settings.buffer,123);assert.match(d.summary.snapshotError,/could not/);assert.equal((await store.get('budget')).book.settings.buffer,123);});

test('startup cleanup persists expired recovery and cancelled occurrences without changing balances',async t=>{const {s,store}=await fixture(t);const old=structuredClone(s.envelope);old.book.deletedBills=[{id:'expired',name:'Old bill',amount:100,date:'2020-01-01',frequency:'Monthly',deletedAt:'2020-01-01',expiresAt:'2020-01-31'}];old.book.deletedPayments=[{id:'expired-payment',amount:100,deletedAt:'2020-01-01',expiresAt:'2020-01-31'}];old.book.overrides['bill@2030-01-01']={status:'Skipped',name:'Old bill',amount:100,deletedAt:'2020-01-01',expiresAt:'2020-01-31'};await store.put('budget',old);const restarted=await new BudgetService(store,()=>{throw Error('No reseed');}).init();const saved=await store.get('budget');assert.deepEqual(saved.book.deletedBills,[]);assert.deepEqual(saved.book.deletedPayments,[]);assert.deepEqual(saved.book.overrides['bill@2030-01-01'],{status:'Cancelled'});assert.equal(restarted.read().summary.cash.balance,s.read().summary.cash.balance);});
