import test from 'node:test';
import assert from 'node:assert/strict';
import {recurringBillSuggestions} from '../analysis.js';
import {fresh,change,summary} from '../server/model.mjs';
const asOf='2026-09-18';
function fixture(dates=['2026-07-20','2026-08-20','2026-09-17']){const b=fresh();b.accounts=[{id:'cash',name:'Checking',kind:'cash',openingBalance:1000,balanceDate:'2026-01-01',verified:true}];b.transactions=dates.map((date,i)=>({id:'t'+i,name:'Stream Box',date,amount:20,accountId:'cash',direction:'Outflow',category:'Entertainment',historical:true}));return b;}
test('monthly suggestions retain supporting history and never alter source data',()=>{const b=fixture(),before=JSON.stringify(b),s=recurringBillSuggestions(b,asOf);assert.equal(s.length,1);assert.equal(s[0].frequency,'Monthly');assert.equal(s[0].next,'2026-10-20');assert.equal(s[0].evidence.length,3);assert.equal(JSON.stringify(b),before);});
test('weekly, biweekly and month-end recurrence',()=>{for(const [dates,f,next,now]of [[['2026-09-03','2026-09-10','2026-09-17'],'Weekly','2026-09-24',asOf],[['2026-08-20','2026-09-03','2026-09-17'],'Biweekly','2026-10-01',asOf],[['2026-01-31','2026-02-28','2026-03-31'],'Monthly','2026-04-30','2026-04-01']]){const [s]=recurringBillSuggestions(fixture(dates),now);assert.equal(s.frequency,f);assert.equal(s.next,next);}});
test('irregular, insufficient, stopped and pending patterns are withheld',()=>{for(const dates of [['2026-09-01','2026-09-02','2026-09-17'],['2026-09-17'],['2026-01-17','2026-02-17','2026-03-17']])assert.equal(recurringBillSuggestions(fixture(dates),asOf).length,0);
 // Two charges a month apart at the same price are a low-confidence suggestion; different prices are not enough.
 const [two]=recurringBillSuggestions(fixture(['2026-08-17','2026-09-17']),asOf);assert.equal(two.confidence,'Low');assert.match(two.note,/twice/);
 const differing=fixture(['2026-08-17','2026-09-17']);differing.transactions[1].amount=21;assert.equal(recurringBillSuggestions(differing,asOf).length,0);const b=fixture();b.transactions[1].pending=true;assert.equal(recurringBillSuggestions(b,asOf).length,0);});
test('transfers, debt payments, corrections and unreviewed candidates cannot suggest bills',()=>{
 // A fixed-amount transfer to someone else (rent by Zelle) is suggested with a warning; a varying one is not.
 {const t=fixture();t.transactions.forEach(x=>x.category='Transfer');const [s]=recurringBillSuggestions(t,asOf);assert.equal(s.confidence,'Medium');assert.match(s.note,/bank transfer/);t.transactions[2].amount=35;assert.equal(recurringBillSuggestions(t,asOf).length,0);}
 // Installment plans (Affirm and similar) are suggested with a warning, even though the bank files them as loan payments.
 {const b=fixture();b.transactions.forEach(t=>{t.category='Debt payment';t.name='AFFIRM * PAY';});const [s]=recurringBillSuggestions(b,asOf);assert.equal(s.confidence,'Medium');assert.match(s.note,/installment/);}
 // A payment to an account you already track as a debt is still not a bill.
 {const b=fixture();b.accounts.push({id:'card',name:'Capital One',kind:'credit',active:true,payment:45});b.transactions.forEach(t=>{t.category='Debt payment';t.name='CAPITAL ONE PAYMENT';});assert.equal(recurringBillSuggestions(b,asOf).length,0);}
 for(const extra of [{category:'Transfer',toAccountId:'s'},{paymentId:'p'},{toAccountId:'s'},{adjustment:true},{direction:'Inflow'}]){const b=fixture();b.transactions.forEach(t=>Object.assign(t,extra));assert.equal(recurringBillSuggestions(b,asOf).length,0);}const b=fixture();b.reviewTransactions=b.transactions;b.transactions=[];assert.equal(recurringBillSuggestions(b,asOf).length,0);});
test('account histories never combine; same-day duplicates withhold a suggestion',()=>{const b=fixture(['2026-06-20','2026-07-20','2026-08-20','2026-09-17']);b.accounts.push({...b.accounts[0],id:'other'});b.transactions[0].accountId='other';b.transactions[2].accountId='other';assert.ok(recurringBillSuggestions(b,asOf).every(s=>s.evidence.every(e=>b.transactions.find(t=>t.id===e.id).accountId===s.accountId)),'evidence never mixes accounts');const c=fixture();c.transactions.push({...c.transactions[2],id:'dupe',historical:false});assert.equal(recurringBillSuggestions(c,asOf).length,0);});
test('existing bills and scheduled debts suppress matching recurring merchants',()=>{const b=fixture();b.bills=[{name:'STREAM-BOX',frequency:'Monthly',active:true}];assert.equal(recurringBillSuggestions(b,asOf).length,0);b.bills=[];b.accounts.push({name:'Stream Box',kind:'credit',payment:20});assert.equal(recurringBillSuggestions(b,asOf).length,0);});
test('accept once changes only future scheduling; dismissal and restore persist',()=>{let b=fixture();const [s]=recurringBillSuggestions(b,asOf),before=summary(b,asOf).cash.balance;const p={key:s.key,mode:'accept',name:s.name,amount:22,date:s.next,frequency:s.frequency};b=change(b,'recurringSuggestion',{key:s.key,mode:'dismiss'},asOf);assert.equal(recurringBillSuggestions(b,asOf)[0].dismissed,true);assert.throws(()=>change(b,'recurringSuggestion',p,asOf),/Restore/);b=change(b,'recurringSuggestion',{key:s.key,mode:'restore'},asOf);b=change(b,'recurringSuggestion',p,asOf);assert.equal(b.bills.length,1);assert.equal(b.bills[0].amount,22);assert.equal(summary(b,asOf).cash.balance,before);assert.deepEqual(b.transactions,fixture().transactions);assert.throws(()=>change(b,'recurringSuggestion',p,asOf),/already/);assert.equal(recurringBillSuggestions(b,asOf).length,0);});
test('variable amounts and stale form edits are explicit and validated',()=>{const b=fixture();b.transactions[2].amount=50;const [s]=recurringBillSuggestions(b,asOf);assert.equal(s.variable,true);assert.equal(s.low,20);assert.equal(s.amount,50);const p={...s,key:s.key,mode:'accept',date:'2026-09-01'};assert.throws(()=>change(b,'recurringSuggestion',p,asOf),/future/);assert.throws(()=>change(b,'recurringSuggestion',{...p,date:asOf,frequency:'One-time'},asOf),/recurring frequency/);});
test('permanent recurring dismissal suppresses the merchant even as the pattern gains charges',()=>{let b=fixture(),s=recurringBillSuggestions(b,asOf)[0];b=change(b,'recurringSuggestion',{key:s.key,mode:'permanent'},asOf);assert.equal(recurringBillSuggestions(b,asOf).length,0);b.transactions.push({id:'t3',name:'Stream Box',date:'2026-10-20',amount:20,accountId:'cash',direction:'Outflow',category:'Entertainment',historical:true});assert.equal(recurringBillSuggestions(b,'2026-10-21').length,0);});
