import test from 'node:test';
import assert from 'node:assert/strict';
import {fresh,change,balances,eventsFor,addDays} from '../server/model.mjs';
import {normalizeRecovery} from '../server/recycle.mjs';
const date='2026-09-16';
function fixture(){let b=fresh();b=change(b,'account',{name:'Cash',kind:'cash',openingBalance:2000,balanceDate:date},date);b=change(b,'account',{name:'Card',kind:'credit',openingBalance:500,balanceDate:date,payment:100,dueDate:date,frequency:'Monthly'},date);return b;}
const amounts=b=>balances(b,date).map(a=>a.balance);
const pay=b=>change(b,'payment',{debtId:b.accounts[1].id,fundingId:b.accounts[0].id,date,amount:100,principal:90},date);
test('deleted payment restores both balances exactly once; repeated restoration is rejected',()=>{let b=pay(fixture()),p=b.payments[0],before=amounts(b);b=change(b,'remove',{list:'payments',id:p.id},date);assert.deepEqual(amounts(b),[2000,500]);assert.equal(b.deletedPayments[0].expiresAt,'2026-10-16');b=change(b,'restorePayment',{id:p.id},date);assert.deepEqual(amounts(b),before);assert.equal(b.deletedPayments.length,0);assert.throws(()=>change(b,'restorePayment',{id:p.id},date),/no longer/);});
for(const removeLinked of [true,false])test('matched payment recovery with linked transaction '+(removeLinked?'deleted':'kept'),()=>{let b=fixture();b=change(b,'transaction',{name:'Card payment',date,amount:100,direction:'Outflow',accountId:b.accounts[0].id,category:'Other'},date);const tx=b.transactions[0];b=change(b,'payment',{debtId:b.accounts[1].id,fundingId:b.accounts[0].id,transactionId:tx.id,date,amount:100,principal:100},date);const before=amounts(b),id=b.payments[0].id;b=change(b,'remove',{list:'payments',id,removeLinked},date);assert.deepEqual(amounts(b),[removeLinked?2000:1900,500]);b=change(b,'restorePayment',{id},date);assert.deepEqual(amounts(b),before);assert.equal(b.transactions.length,1);assert.equal(b.transactions[0].paymentId,id);assert.equal(b.payments[0].fundingId,'');});
test('recovery refuses changed matches, missing accounts, later balance corrections and overpayment',()=>{let b=pay(fixture()),id=b.payments[0].id;b=change(b,'remove',{list:'payments',id},date);let c=change(b,'reconcile',{id:b.accounts[0].id,balance:2100},date);assert.throws(()=>change(c,'restorePayment',{id},date),/corrected/);c=change(b,'payment',{debtId:b.accounts[1].id,date,amount:450,principal:450},date);assert.throws(()=>change(c,'restorePayment',{id},date),/no longer fits/);c=change(b,'remove',{list:'accounts',id:b.accounts[1].id},date);assert.throws(()=>change(c,'restorePayment',{id},date),/debt account/);});
test('a transaction edited after unlinking cannot be silently overwritten by recovery',()=>{let b=fixture();b=change(b,'transaction',{name:'Payment',date,amount:100,direction:'Outflow',accountId:b.accounts[0].id,category:'Other'},date);const tx=b.transactions[0];b=change(b,'payment',{debtId:b.accounts[1].id,fundingId:b.accounts[0].id,transactionId:tx.id,date,amount:100,principal:100},date);const id=b.payments[0].id;b=change(b,'remove',{list:'payments',id},date);b=change(b,'category',{id:tx.id,category:'Shopping'},date);assert.throws(()=>change(b,'restorePayment',{id},date),/transaction changed/);});
test('expiry removes recovery entries without bringing skipped future debt occurrences back',()=>{let b=pay(fixture());b=change(b,'remove',{list:'payments',id:b.payments[0].id},date);const later='2026-11-16',key=b.accounts[1].id+'@'+later;b=change(b,'occurrence',{key,date:later,status:'Skipped'},date);b=change(b,'bill',{name:'Power',date,amount:50,frequency:'Monthly'},date);b=change(b,'remove',{list:'bills',id:b.bills[0].id},date);const before=amounts(b);assert.equal(normalizeRecovery(b,'2026-10-15').deletedPayments.length,1);b=normalizeRecovery(b,'2026-10-16');assert.equal(b.deletedPayments.length,0);assert.equal(b.deletedBills.length,0);assert.deepEqual(b.overrides[key],{status:'Cancelled'});assert.deepEqual(amounts(b),before);assert.ok(!eventsFor(b,later,later,date).some(e=>e.key===key));assert.throws(()=>change(b,'restoreOccurrence',{key},'2026-10-16'),/no longer/);assert.ok(eventsFor(b,'2026-12-16','2026-12-16',date).length);});
test('old deleted bills receive a full window on upgrade and restored bills lose deletion metadata',()=>{let b=fixture();b.deletedBills=[{id:'old',name:'Internet',date,amount:20,frequency:'Monthly'}];b=normalizeRecovery(b,date);assert.equal(b.deletedBills[0].expiresAt,addDays(date,30));b=change(b,'restoreBill',{id:'old'},date);assert.equal(b.deletedBills.length,0);assert.equal(b.bills[0].deletedAt,undefined);});
test('permanent removal leaves finances unchanged and cannot unskip an occurrence',()=>{let b=pay(fixture());b=change(b,'remove',{list:'payments',id:b.payments[0].id},date);const id=b.deletedPayments[0].id,key=b.accounts[1].id+'@'+date;b=change(b,'occurrence',{key,date,status:'Skipped'},date);const before=amounts(b);b=change(b,'purgePayment',{id},date);b=change(b,'purgeOccurrence',{key},date);assert.deepEqual(amounts(b),before);assert.equal(b.deletedPayments.length,0);assert.ok(!eventsFor(b,date,date,date).length);});
for(const useCredit of [false,true])test('deleted paid-bill transaction can be restored once to '+(useCredit?'credit':'cash'),()=>{let b=fixture();b=change(b,'bill',{name:'Internet',amount:50,date,frequency:'Monthly'},date);const key=b.bills[0].id+'@'+date;b=change(b,'occurrence',{key,date,status:'Paid',accountId:b.accounts[useCredit?1:0].id},date);const before=amounts(b),id=b.transactions[0].id;b=change(b,'remove',{list:'transactions',id},date);assert.deepEqual(amounts(b),[2000,500]);assert.ok(eventsFor(b,date,date,date).some(e=>e.key===key));assert.equal(b.deletedPayments[0].recordType,'bill');b=change(b,'restoreBillPayment',{id},date);assert.deepEqual(amounts(b),before);assert.ok(!eventsFor(b,date,date,date).some(e=>e.key===key));assert.equal(b.deletedPayments.length,0);assert.throws(()=>change(b,'restoreBillPayment',{id},date),/no longer/);});
test('paid-bill recovery refuses a bill that was paid again or later corrected',()=>{let b=fixture();b=change(b,'bill',{name:'Internet',amount:50,date,frequency:'Monthly'},date);const key=b.bills[0].id+'@'+date,accountId=b.accounts[0].id;b=change(b,'occurrence',{key,date,status:'Paid',accountId},date);const id=b.transactions[0].id;b=change(b,'remove',{list:'transactions',id},date);const paid=change(b,'occurrence',{key,date,status:'Paid',accountId},date);assert.throws(()=>change(paid,'restoreBillPayment',{id},date),/already paid/);const corrected=change(b,'reconcile',{id:accountId,balance:2100},date);assert.throws(()=>change(corrected,'restoreBillPayment',{id},date),/balance changed/);});
