import test from 'node:test';
import assert from 'node:assert/strict';
import {fresh,change,summary,eventsFor} from '../server/model.mjs';
import {yearlyReport,deliverYearlyReview} from '../server/review-mail.mjs';
const day='2026-09-15';
function budget(){let b=fresh();for(const [name,kind,openingBalance]of [['Checking','cash',2000],['Card','credit',300]])b=change(b,'account',{name,kind,openingBalance,balanceDate:'2025-01-01'},day);return b;}
test('card-paid bills increase debt once, leave cash intact and restore on removal',()=>{let b=budget();b=change(b,'bill',{name:'Internet',amount:80,date:day,frequency:'Monthly',category:'Utilities'},day);const key=b.bills[0].id+'@'+day,p={key,date:day,status:'Paid',accountId:b.accounts[1].id};b=change(b,'occurrence',p,day);assert.equal(summary(b,day).cash.balance,2000);assert.equal(summary(b,day).accounts[1].balance,380);assert.equal(eventsFor(b,day,day,day).length,0);assert.throws(()=>change(b,'occurrence',p,day),/no longer active/);b=change(b,'remove',{list:'transactions',id:b.transactions[0].id},day);assert.equal(summary(b,day).accounts[1].balance,300);assert.equal(eventsFor(b,day,day,day).length,1);});
test('scheduled debt requires a due date and appears in Calendar after save and reload',()=>{let b=budget();const data={...b.accounts[1],payment:50,frequency:'Monthly'};assert.throws(()=>change(b,'account',data,day),/due date/);b=change(b,'account',{...data,dueDate:'2026-09-20'},day);b=JSON.parse(JSON.stringify(b));assert.equal(eventsFor(b,'2026-09-01','2026-09-30',day)[0].amount,50);assert.equal(eventsFor(b,'2026-10-01','2026-10-31',day)[0].date,'2026-10-20');});
test('color preferences, buffer and hidden scenarios persist independently',()=>{let b=budget();const colors=Object.fromEntries(['utilities','groceries','dining-out','transportation','housing','medical','entertainment','insurance','pets','personal-care','services','education','donations','bank-fees','taxes','debt-payment','other'].map(k=>[k,'#123456']));b=change(b,'expenseColors',colors,day);b=change(b,'cashBuffer',{buffer:450},day);b=change(b,'hideScenario',{extra:25},day);b=change(b,'hideScenario',{extra:25},day);b=JSON.parse(JSON.stringify(b));assert.deepEqual(b.settings.expenseColors,colors);assert.equal(b.settings.buffer,450);assert.deepEqual(b.settings.hiddenScenarios,[25]);assert.throws(()=>change(b,'expenseColors',{...colors,transportation:'url(https://invalid)'},day),/valid color/);});
test('wish priority and custom waiting days persist, and Needs become categorized bills',()=>{let b=budget();b=change(b,'wish',{name:'Camera',cost:200,priority:'High'},day);b=change(b,'wish',{...b.wishes[0],saved:10},day);assert.equal(b.wishes[0].priority,'High');b=change(b,'cooling',{name:'Camera',cost:200,wishId:b.wishes[0].id,days:12},day);assert.equal(b.cooling[0].date,'2026-09-27');assert.throws(()=>change(b,'cooling',{name:'Camera',cost:200,days:1.5},day),/whole/);b=change(b,'need',{name:'New car tires',cost:200,urgency:'High',mode:'schedule',date:day},day);assert.equal(b.needs.length,0);assert.equal(b.bills[0].category,'Car');});
test('yearly reports exclude corrections and count linked payments once',()=>{let b=budget();const put=(a,p)=>b=change(b,a,p,day);put('transaction',{name:'Pay',amount:1000,date:'2025-02-01',direction:'Inflow',accountId:b.accounts[0].id,category:'Income'});put('transaction',{name:'Food',amount:50,date:'2025-02-02',direction:'Outflow',accountId:b.accounts[0].id,category:'Groceries'});put('transaction',{name:'Pay card',amount:80,date:'2025-02-03',direction:'Outflow',accountId:b.accounts[0].id,category:'Other'});put('payment',{debtId:b.accounts[1].id,fundingId:b.accounts[0].id,transactionId:b.transactions[2].id,amount:80,principal:80,date:'2025-02-03'});const r=yearlyReport(b,summary(b,day),2025);assert.equal(r.income,1000);assert.equal(r.spending,50);assert.equal(r.payments,80);assert.equal(r.net,870);assert.equal(r.periodType,'yearly');});
test('yearly email requires a recipient, honors opt-in and sample mode, and attempts once',async()=>{let b=budget();assert.throws(()=>change(b,'reviewPreferences',{yearly:true,email:''},day),/recipient/);b=change(b,'reviewPreferences',{yearly:true,enabled:false,email:'owner@example.com'},day);b=change(b,'transaction',{name:'Food',amount:20,date:'2025-02-02',direction:'Outflow',accountId:b.accounts[0].id,category:'Groceries'},day);const map=new Map(),store={get:async k=>map.get(k),put:async(k,v)=>map.set(k,v)};let calls=0;const send=async()=>{calls++;throw Error('Uncertain delivery');};b.sampleMode=true;await deliverYearlyReview(store,b,summary(b,day),{},send);assert.equal(calls,0);b.sampleMode=false;await deliverYearlyReview(store,b,summary(b,day),{},send);await deliverYearlyReview(store,b,summary(b,day),{},send);assert.equal(calls,1);assert.ok(map.has('mail-year-2025'));});
