import test from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';
import {fresh,change,summary} from '../server/model.mjs';
import {incomeEstimate,cleanHistory,spendingAnalysis,debtSimulation,allocatePaycheck,savingsPlans,monthlyReport} from '../analysis.js';
import {deliverMonthlyReview,sendReview,sendTestMail,validateMail} from '../server/review-mail.mjs';
const day='2026-09-15';
function fixture(){let b=fresh();b=change(b,'account',{name:'Cash',kind:'cash',openingBalance:5000,balanceDate:'2026-01-01'},day);b=change(b,'account',{name:'Card',kind:'credit',openingBalance:1000,balanceDate:'2026-01-01',payment:100,limit:3000,dueDate:'2026-09-20',frequency:'Monthly',apr:24},day);b=change(b,'settings',{buffer:400,planningConfirmed:true},day);b=change(b,'incomeProfile',{name:'Work',amount:800,date:day,frequency:'Weekly',estimateMode:'conservative'},day);return b;}
function deposits(b){for(const [i,amount]of [900,1000,1100].entries())b.transactions.push({id:'pay'+i,name:'Work',amount,date:['2026-08-25','2026-09-01','2026-09-08'][i],direction:'Inflow',category:'Income',accountId:b.accounts[0].id,historical:true});return b;}
test('income estimate and recorded expectation share the conservative forecast amount',()=>{let b=deposits(fixture());const i=b.incomes[0],e=incomeEstimate(b,i,day);assert.equal(e.typical,1000);assert.equal(e.conservative,918.35);assert.equal(e.cadence,7);assert.equal(summary(b,day).nextPaychecks[0].amount,e.amount);b=change(b,'receiveIncome',{addToBalance:true,id:i.id,date:day,amount:950,accountId:b.accounts[0].id},day);assert.equal(b.transactions.at(-1).incomeExpectation.amount,e.amount);assert.equal(b.incomes[0].date,'2026-09-22');assert.equal(summary(b,day).cash.balance,5950);});
test('ambiguous deposits are withheld until reviewed; source identities do not overlap',()=>{let b=deposits(fixture());b.transactions.push({...b.transactions[0],id:'copy'});assert.equal(cleanHistory(b,day).ignored.length,2);assert.equal(incomeEstimate(b,b.incomes[0],day).amount,800);b.dismissedDuplicates=['copy|pay0'];assert.equal(cleanHistory(b,day).ignored.length,0);assert.throws(()=>change(b,'incomeProfile',{name:'Other',historyName:'Work',amount:100,date:day,frequency:'Weekly',estimateMode:'average'},day),/distinct/);b.transactions[1].incomeExpectation={scheduleId:'someone-else'};assert.equal(incomeEstimate(b,b.incomes[0],day).count,3);});
test('wage schedules affect forecast without inserting deposits',()=>{let b=fixture();b=change(b,'incomeProfile',{id:b.incomes[0].id,name:'Work',amount:800,date:day,frequency:'Biweekly',estimateMode:'wages',hourlyRate:20,hoursPerWeek:40,takeHomePercent:75},day);assert.equal(summary(b,day).nextPaychecks[0].amount,1200);assert.equal(b.transactions.length,0);});
test('surplus allocations sum to available cash and respect buffer shortfalls',()=>{let b=fixture(),s=summary(b,day),a=allocatePaycheck(b,s);assert.equal(Object.values(a.parts).reduce((n,v)=>n+v,0),a.surplus);assert.ok(a.surplus<=a.amount);assert.throws(()=>change(b,'allocationSettings',{debt:100,sinking:100,goals:0,wishes:0,flex:0},day),/total 100/);// A dip below the buffer before payday no longer cancels the plan: the projection after payday decides.
 const dipped=structuredClone(s);dipped.plan.forecast.unshift({date:'2026-09-14',cash:10});
 assert.ok(allocatePaycheck(b,dipped).surplus>0,'a low but positive balance still allows a plan');
 const overdrawn=structuredClone(s);overdrawn.plan.forecast.unshift({date:'2026-09-14',cash:-10});
 assert.equal(allocatePaycheck(b,overdrawn).surplus,0,'running out of cash still stops it');});
test('Next Target receives two automatic shares while custom savings cannot expand the pool',()=>{let b=fixture();for(const name of ['A','B'])b=change(b,'wish',{name,cost:300,saved:0,style:'Automatic'},day);b=change(b,'goalFocus',{list:'wishes',id:b.wishes[0].id,mode:'automatic'},day);const projections=savingsPlans(b,summary(b,day));assert.ok(projections[0].weekly>projections[1].weekly);assert.ok(projections[1].weekly>0);assert.ok(Math.abs(projections[0].weekly-2*projections[1].weekly)<=.02);b.wishes.push({id:'custom',name:'Custom',cost:500,saved:0,style:'Custom',weekly:500});const over=savingsPlans(b,summary(b,day));assert.ok(over.every(v=>v.overallocated));assert.equal(over[0].weekly,0);});
test('scheduling a target releases its reserve and adds exactly one full-cost bill',()=>{let b=fixture();b=change(b,'wish',{name:'Camera',cost:500,saved:200,style:'Custom',weekly:20},day);const id=b.wishes[0].id,before=summary(b,day);b=change(b,'completeTarget',{id,list:'wishes',mode:'schedule',date:'2026-09-16'},day);assert.equal(b.wishes.length,0);assert.equal(b.bills.length,1);assert.equal(b.bills[0].amount,500);assert.equal(summary(b,day).cash.balance,before.cash.balance);assert.equal(summary(b,day).protectedSavings,0);assert.throws(()=>change(b,'completeTarget',{id,list:'wishes',mode:'schedule',date:'2026-09-16'},day),/not found/);});
test('a target purchase matches an existing outflow instead of deducting cash twice',()=>{let b=fixture();b=change(b,'wish',{name:'Camera',cost:500,saved:200,style:'Custom',weekly:20},day);b=change(b,'transaction',{name:'Shop',amount:500,date:day,accountId:b.accounts[0].id,direction:'Outflow',category:'Shopping'},day);const before=summary(b,day).cash.balance;b=change(b,'completeTarget',{id:b.wishes[0].id,list:'wishes',mode:'purchased',date:day,accountId:b.accounts[0].id,transactionId:b.transactions[0].id},day);assert.equal(summary(b,day).cash.balance,before);assert.equal(b.transactions.length,1);assert.equal(b.targetHistory.length,1);});
test('debt scenarios roll payments, reduce interest, and report non-amortizing debt',()=>{const accounts=[{id:'a',name:'A',kind:'credit',balance:1000,payment:100,frequency:'Monthly',apr:24},{id:'b',name:'B',kind:'loan',balance:400,payment:50,frequency:'Monthly',apr:5}];const base=debtSimulation(accounts),extra=debtSimulation(accounts,50);assert.ok(extra.months<base.months);assert.ok(extra.interest<base.interest);assert.equal(debtSimulation([{...accounts[0],payment:0}]).limited,true);assert.equal(debtSimulation([{...accounts[0],balance:100,apr:0,payment:100}]).months,1);});
test('monthly cash flow counts card spending and payments on their correct ledgers',()=>{let b=fixture();b=change(b,'transaction',{name:'Card purchase',amount:200,date:day,accountId:b.accounts[1].id,direction:'Outflow',category:'Shopping'},day);b=change(b,'transaction',{name:'Payment',amount:100,date:day,accountId:b.accounts[0].id,direction:'Outflow',category:'Other'},day);b=change(b,'payment',{debtId:b.accounts[1].id,amount:100,principal:90,date:day,fundingId:b.accounts[0].id,transactionId:b.transactions[1].id},day);const r=monthlyReport(b,summary(b,day),'2026-09');assert.equal(r.spending,200);assert.equal(r.payments,100);assert.equal(r.net,-100);b=change(b,'payment',{debtId:b.accounts[1].id,amount:50,principal:50,date:day,fundingId:b.accounts[0].id},day);assert.equal(monthlyReport(b,summary(b,day),'2026-09').net,-150);});
test('watchdog finds consistent price rises and small repeats without duplicate inflation',()=>{const b=fixture();for(const [i,date]of ['2026-06-15','2026-07-15','2026-08-15','2026-09-15'].entries())b.transactions.push({id:'sub'+i,accountId:b.accounts[0].id,name:'Stream',date,amount:i===3?20:10,direction:'Outflow',category:'Entertainment',historical:true});const a=spendingAnalysis(b,day);assert.equal(a.recurring[0].signal,'Price increase');assert.equal(a.heatmap.Entertainment[8],20);});
test('renewal metadata keeps bill and forecast amount intact',()=>{let b=fixture();b=change(b,'bill',{name:'Insurance',amount:100,date:day,frequency:'Monthly'},day);b=change(b,'renewalMeta',{id:b.bills[0].id,date:'2026-12-01',reviewBy:'2026-11-15',status:'Contacted',potentialSavings:20,autoRenew:true,negotiable:true},day);assert.equal(b.bills[0].amount,100);assert.equal(b.bills[0].renewal.status,'Contacted');assert.throws(()=>change(b,'renewalMeta',{id:b.bills[0].id,date:'2026-12-01',reviewBy:'2026-12-15',status:'Review'},day),/on or before/);});
const memory=()=>{const map=new Map();return {get:async k=>map.get(k),put:async(k,v)=>map.set(k,v)};};
test('mail is opt-in, never sends samples, and makes one attempt per month',async()=>{let b=deposits(fixture()),calls=0;const send=async()=>{calls++;},store=memory();await deliverMonthlyReview(store,b,summary(b,day),{},send);assert.equal(calls,0);b.settings.reviewEmail={enabled:true,email:'owner@example.com'};b.sampleMode=true;await deliverMonthlyReview(store,b,summary(b,day),{},send);assert.equal(calls,0);b.sampleMode=false;await deliverMonthlyReview(store,b,summary(b,day),{},send);await deliverMonthlyReview(store,b,summary(b,day),{},send);assert.equal(calls,1);});
test('uncertain email failures are not retried automatically',async()=>{const b=deposits(fixture());b.settings.reviewEmail={enabled:true,email:'owner@example.com'};let calls=0;const store=memory(),send=async()=>{calls++;throw Error('Disconnected after DATA');};assert.match(await deliverMonthlyReview(store,b,summary(b,day),{},send),/uncertain/);await deliverMonthlyReview(store,b,summary(b,day),{},send);assert.equal(calls,1);assert.throws(()=>validateMail({host:'mail.example.com',from:'me@example.com\r\nBcc: other@example.com',user:'u',password:'p'}),/valid email/);});
test('SMTP submission handles multiline capabilities and uses required TLS options',async()=>{let options;const commands=[];class Socket extends EventEmitter{setTimeout(){}destroy(){}end(){}write(text){commands.push(text);const response=text.startsWith('EHLO')?'250-test\r\n250-AUTH PLAIN LOGIN\r\n250 OK\r\n':text.startsWith('AUTH')?'235 OK\r\n':text==='DATA\r\n'?'354 Continue\r\n':'250 OK\r\n';queueMicrotask(()=>this.emit('data',Buffer.from(response)));}}const connector=o=>{options=o;const s=new Socket();queueMicrotask(()=>s.emit('data',Buffer.from('220 Hello\r\n')));return s;};await sendReview({host:'smtp.example.com',from:'me@example.com',user:'me',password:'private'},'me@example.com',{month:'2026-08',income:100,spending:10,payments:20,net:70,withheld:0},connector);assert.equal(options.port,465);assert.equal(options.rejectUnauthorized,true);assert.equal(options.minVersion,'TLSv1.2');assert.ok(commands.some(c=>c.startsWith('Subject:')||c.includes('\r\nSubject: Budget HQ')));});
test('dismissing an insight preserves required review actions and supports restore',async()=>{const {analyzeBudget}=await import('../analysis.js');let b=fixture();let s=summary(b,day),a=analyzeBudget(b,s);const issue=a.issues[0];assert.ok(issue);b=change(b,'insightState',{id:issue.id,status:'dismissed'},day);assert.ok(!analyzeBudget(b,s).issues.some(i=>i.id===issue.id));b=change(b,'insightState',{id:issue.id,status:'reset'},day);assert.ok(analyzeBudget(b,s).issues.some(i=>i.id===issue.id));assert.equal(summary(b,day).ready,true);});
test('current account edit preserves opening records and adds exactly one correction',()=>{let b=fixture();b=change(b,'payment',{debtId:b.accounts[1].id,amount:100,principal:90,date:day,fundingId:b.accounts[0].id},day);const a=b.accounts[0],opening=a.openingBalance;b=change(b,'editAccount',{...a,currentBalance:4500},day);assert.equal(b.accounts[0].openingBalance,opening);assert.equal(summary(b,day).cash.balance,4500);assert.equal(b.payments.length,1);assert.equal(b.transactions.filter(t=>t.adjustment).length,1);b=change(b,'editAccount',{...b.accounts[0],currentBalance:4500},day);assert.equal(b.transactions.filter(t=>t.adjustment).length,1);assert.equal(summary(b,day).plan.forecast.length,60);});
test('need scheduling refuses the past and attention remains until all needs scheduled',async()=>{const {attentionItems}=await import('../workflow.js');let b=fixture();for(const urgency of ['High','Low'])b=change(b,'need',{name:urgency,cost:100,urgency},day);let n=b.needs[0];assert.throws(()=>change(b,'need',{...n,mode:'schedule',date:'2026-09-14'},day),/today or a future/);assert.match(attentionItems(b,summary(b,day)).find(x=>x.key==='needs').detail,/1 high.*1 low/);b=change(b,'need',{...n,mode:'schedule',date:day},day);assert.ok(attentionItems(b,summary(b,day)).some(x=>x.key==='needs'));b=change(b,'need',{...b.needs[0],mode:'schedule',date:day},day);assert.ok(!attentionItems(b,summary(b,day)).some(x=>x.key==='needs'));});

test('wish saving starts once the projected balance clears the buffer',()=>{
 let b=fresh();const day2='2026-09-22';
 b=change(b,'account',{name:'SCU Checking',kind:'cash',openingBalance:250,balanceDate:'2026-01-01'},day2);
 b=change(b,'settings',{buffer:300,planningConfirmed:true},day2);
 b=change(b,'income',{name:'Alamo Drafthouse',amount:1500,date:'2026-09-25',frequency:'Biweekly'},day2);
 b=change(b,'bill',{name:'Internet',amount:60,date:'2026-09-28',frequency:'Monthly'},day2);
 b=change(b,'wish',{name:'Concert tickets',cost:400},day2);
 const s=summary(b,day2);
 assert.ok(s.cash.balance<s.cash.bufferTarget,'today the cash is below the buffer');
 const plan=allocatePaycheck(b,s);
 assert.ok(plan.parts.wishes>0,'the paycheck plan puts something towards wishes');
 assert.equal(plan.wishBufferHold,0,'nothing is held back for the buffer');
 // If the projection still sits below the buffer after payday, wishes keep waiting.
 const tight=structuredClone(s);tight.plan.forecast=tight.plan.forecast.map(p=>({...p,cash:Math.min(p.cash,250)}));
 assert.equal(allocatePaycheck(b,tight).parts.wishes,0);
});

test('test email sends no budget information and is labeled as a test',async()=>{const commands=[];class Socket extends EventEmitter{setTimeout(){}destroy(){}end(){}write(value){commands.push(value);const response=value.startsWith('EHLO')?'250-test\r\n250-AUTH PLAIN\r\n250 OK\r\n':value.startsWith('AUTH')?'235 OK\r\n':value==='DATA\r\n'?'354 Continue\r\n':'250 OK\r\n';queueMicrotask(()=>this.emit('data',Buffer.from(response)));}}const connector=()=>{const socket=new Socket();queueMicrotask(()=>socket.emit('data',Buffer.from('220 Hello\r\n')));return socket;};await sendTestMail({host:'smtp.example.com',from:'me@example.com',user:'me',password:'private'},'me@example.com',connector);const sent=commands.find(c=>c.includes('Subject: Budget HQ test email'));assert.ok(sent);assert.doesNotMatch(sent,/Recorded income|Recorded spending/);assert.match(Buffer.from(sent.split('\r\n\r\n')[1].split('\r\n.')[0].replace(/\r\n/g,''),'base64').toString(),/No budget information is included/);});
