import test from 'node:test';
import assert from 'node:assert/strict';
import {fresh,change,summary} from '../server/model.mjs';
import {effectiveSavingsStyle,savingsPlans,allocatePaycheck} from '../analysis.js';
const day='2026-09-16';
function fixture(){let b=fresh();b=change(b,'account',{name:'Cash',kind:'cash',openingBalance:10000,balanceDate:day},day);b=change(b,'income',{name:'Pay',amount:1000,date:day,frequency:'Weekly'},day);b=change(b,'settings',{buffer:100,planningConfirmed:true},day);b=change(b,'wish',{name:'Camera',cost:500,saved:100,style:'Custom',weekly:20},day);return b;}
test('Dated pauses stop savings suggestions and resume the prior method without moving money',()=>{let b=fixture();const id=b.wishes[0].id;b=change(b,'wish',{...b.wishes[0],id,style:'Pause',pauseUntil:'2026-09-20'},day);assert.equal(b.wishes[0].resumeStyle,'Custom');const before=JSON.stringify(b);assert.equal(savingsPlans(b,summary(b,day))[0].weekly,0);assert.equal(savingsPlans(b,summary(b,'2026-09-20'))[0].weekly,20);assert.equal(effectiveSavingsStyle(b.wishes[0],'2026-09-20'),'Custom');assert.equal(summary(b,'2026-09-20').cash.balance,10000);assert.equal(b.wishes[0].saved,100);assert.equal(JSON.stringify(b),before);});
test('Blank pause dates remain paused; past dates are rejected and a manual resume clears the date',()=>{let b=fixture();b=change(b,'wish',{...b.wishes[0],style:'Pause',pauseUntil:''},day);assert.equal(effectiveSavingsStyle(b.wishes[0],'2030-01-01'),'Pause');assert.throws(()=>change(b,'wish',{...b.wishes[0],pauseUntil:day},day),/future resume date/);assert.throws(()=>change(b,'wish',{...b.wishes[0],pauseUntil:'bad-date'},day));b=change(b,'wish',{...b.wishes[0],style:'Automatic',pauseUntil:'2026-09-20'},day);assert.equal(b.wishes[0].pauseUntil,'');assert.equal(effectiveSavingsStyle(b.wishes[0],day),'Automatic');});
test('Pause action supports indefinite or dated pauses; Unpause restores savings and clears legacy waiting',()=>{let b=fixture(),id=b.wishes[0].id;b.cooling=[{id:'legacy',wishId:id,date:'2026-10-01'}];b=change(b,'wishPause',{id,pauseUntil:''},day);assert.equal(b.cooling.length,0);assert.equal(effectiveSavingsStyle(b.wishes[0],'2027-01-01'),'Pause');assert.equal(savingsPlans(b,summary(b,day))[0].weekly,0);b=change(b,'wishResume',{id},day);b=change(b,'wishResume',{id},day);assert.equal(b.wishes[0].style,'Custom');assert.equal(b.wishes[0].weekly,20);assert.equal(b.wishes[0].saved,100);assert.equal(summary(b,day).cash.balance,10000);assert.throws(()=>change(b,'wishPause',{id,pauseUntil:day},day),/future resume date/);b=change(b,'wishPause',{id,pauseUntil:'2026-09-20'},day);assert.equal(savingsPlans(b,summary(b,'2026-09-20'))[0].weekly,20);});
test('Legacy Think It Over records are paused and can be unpaused without losing wish details',()=>{let b=fixture(),id=b.wishes[0].id;b.cooling=[{id:'old',wishId:id,date:'2026-09-22'}];assert.equal(savingsPlans(b,summary(b,day))[0].weekly,0);b=change(b,'wishResume',{id},day);assert.equal(b.cooling.length,0);assert.equal(savingsPlans(b,summary(b,day))[0].weekly,20);assert.equal(b.wishes[0].name,'Camera');});


test('buffer no longer auto-pauses wishes; manual pauses and saved money remain intact',()=>{
 let b=fixture();b=change(b,'wish',{name:'Second wish',cost:500,saved:0,style:'Custom',weekly:10},day);b.settings.pauseWishesBelowBuffer=true;b=change(b,'reconcile',{id:b.accounts[0].id,balance:50},day);
 let data=summary(b,day),plans=savingsPlans(b,data);assert.equal(plans[0].weekly,20);assert.equal(plans[1].weekly,10);assert.equal(data.protectedSavings,100);assert.equal(allocatePaycheck(b,data).wishBufferHold,0);
 b=change(b,'wishPause',{id:b.wishes[0].id},day);b=JSON.parse(JSON.stringify(b));plans=savingsPlans(b,summary(b,day));assert.equal(plans[0].weekly,0);assert.equal(plans[1].weekly,10);
});
