import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,change,summary,balances} from '../server/model.mjs';
import {weekStart,reviewState,changeDescription,tripFieldVisible} from '../workflow.js';
const day='2026-09-15';
function seed(){let b=fresh();b=change(b,'account',{name:'Cash',kind:'cash',openingBalance:1000,balanceDate:day},day);b=change(b,'account',{name:'Card',kind:'credit',openingBalance:500,balanceDate:day,payment:50,dueDate:day},day);return change(b,'settings',{buffer:100,planningConfirmed:true},day);}
test('review match removes only the duplicate cash deduction and supports undo by deletion',()=>{let b=seed();b=change(b,'payment',{debtId:b.accounts[1].id,fundingId:b.accounts[0].id,amount:50,principal:40,date:day},day);b=change(b,'transaction',{accountId:b.accounts[0].id,name:'Card payment',amount:50,direction:'Outflow',date:day},day);assert.deepEqual(balances(b,day).map(a=>a.balance),[900,460]);const queue=reviewState(b);assert.equal(queue.matches.length,1);b=change(b,'matchPayment',{id:b.payments[0].id,transactionId:b.transactions[0].id},day);assert.deepEqual(balances(b,day).map(a=>a.balance),[950,460]);assert.equal(reviewState(b).matches.length,0);assert.throws(()=>change(b,'matchPayment',{id:b.payments[0].id,transactionId:b.transactions[0].id},day));});
test('duplicate suggestions never delete records, and confirmed separate purchases leave Review',()=>{let b=seed();for(let i=0;i<2;i++)b=change(b,'transaction',{accountId:b.accounts[0].id,name:'Coffee',amount:5,direction:'Outflow',date:day},day);const group=reviewState(b).duplicates[0];assert.equal(b.transactions.length,2);const before=balances(b,day)[0].balance;b=change(b,'dismissDuplicate',{key:group.key},day);assert.equal(reviewState(b).duplicates.length,0);assert.equal(balances(b,day)[0].balance,before);assert.equal(b.transactions.length,2);});
test('historical transactions are excluded from cash-payment match suggestions',()=>{let b=seed();b=change(b,'payment',{debtId:b.accounts[1].id,fundingId:b.accounts[0].id,amount:50,principal:40,date:day},day);b=change(b,'transaction',{accountId:b.accounts[0].id,name:'Old payment',amount:50,direction:'Outflow',date:day,historical:true},day);assert.equal(reviewState(b).matches.length,0);});
test('weekly check-in survives serialized reload without adding income or payments',()=>{let b=seed();const before=JSON.stringify([b.transactions,b.incomes,b.payments]);const p={balancesReviewed:true,billsReviewed:true,incomeReviewed:true,schedule:'same'};b=change(b,'checkin',p,day);b=JSON.parse(JSON.stringify(b));assert.equal(b.checkins[0].week,'2026-09-14');assert.equal(JSON.stringify([b.transactions,b.incomes,b.payments]),before);b=change(b,'checkin',{...p,schedule:'changed',notes:'Extra shift'},day);assert.equal(b.checkins.length,1);assert.equal(b.checkins[0].schedule,'changed');assert.equal(b.accounts[0].confirmedAt,day);});
test('incomplete weekly check-in is rejected; Sunday belongs to the same Monday week',()=>{const b=seed();assert.throws(()=>change(b,'checkin',{balancesReviewed:true,billsReviewed:false,incomeReviewed:true,schedule:'same'},day),/Review balances/);assert.equal(weekStart('2026-09-20'),'2026-09-14');assert.equal(weekStart('2026-09-21'),'2026-09-21');});
test('editing APR alone never claims the current balance was checked today',()=>{let b=seed();b=change(b,'account',{...b.accounts[1],apr:25},'2026-09-16');assert.equal(b.accounts[1].confirmedAt,day);b=change(b,'reconcile',{id:b.accounts[1].id,balance:500},'2026-09-16');assert.equal(b.accounts[1].confirmedAt,'2026-09-16');});
test('change confirmation states the actual safe-to-spend difference',()=>{let b=seed();b=change(b,'bill',{name:'Internet',amount:60,date:day,frequency:'Monthly'},day);const before=summary(b,day);b=change(b,'occurrence',{key:b.bills[0].id+'@'+day,date:day,status:'Skipped'},day);assert.match(changeDescription(before,summary(b,day),'occurrence'),/increased by \$60.00/);before.ready=false;assert.doesNotMatch(changeDescription(before,summary(b,day),'occurrence'),/increased/);});
test('flight, driving and rental fields appear only when relevant',()=>{assert.equal(tripFieldVisible('flightFare','Drive',false),false);assert.equal(tripFieldVisible('fuelPrice','Drive',false),true);assert.equal(tripFieldVisible('rentalRate','Fly',false),false);assert.equal(tripFieldVisible('rentalRate','Fly',true),true);assert.equal(tripFieldVisible('hotelRate','Fly',false),true);});
