import {occurrences} from './schedule.js';
// Financial goals describe progress; calculations never create money or payments.
const round=n=>Math.round(n*100)/100;
export function essentialMonthly(book){const factors={Weekly:52/12,Biweekly:26/12,Monthly:1,Quarterly:1/3,Yearly:1/12};return round(book.bills.filter(b=>b.active!==false&&/housing|rent|food|groc|util|transport|medical|vet|^car$/i.test(b.category||'')).reduce((s,b)=>s+(factors[b.frequency]||0)*Number(b.amount||0),0)+book.accounts.filter(a=>a.active!==false&&a.kind!=='cash').reduce((s,a)=>s+(factors[a.frequency]||0)*Number(a.payment||0),0));}
export function goalTarget(g,book){return g.goalType==='emergency'?round((g.expenseMode==='custom'?Number(g.monthlyEssentials):essentialMonthly(book))*Number(g.months||3)):Number(g.cost||0);}
export function utilizationPercent(g,account){if(account?.kind!=='credit'||g.targetMode==='balance')return null;const explicit=Number(g.targetUtilization),legacy=String(g.name||'').match(/\bget to (\d+(?:\.\d+)?)% utilization\b/i),value=g.targetUtilization!==undefined&&g.targetUtilization!==null&&g.targetUtilization!==''?explicit:legacy?Number(legacy[1]):null;return value!==null&&Number.isFinite(value)&&value>=0&&value<=100?value:null;}
export function debtGoalTarget(g,account){const percent=utilizationPercent(g,account);return percent!==null&&Number(account?.limit)>0?round(Number(account.limit)*percent/100):Number(g.targetBalance||0);}
export function goalPaydays(book,start,end){const dates=new Set();for(const income of book.incomes.filter(i=>i.active!==false&&i.verified!==false)){if(!income.date)continue;for(const day of occurrences(income.date,income.frequency,start,end))if(!['Skipped','Cancelled','Paid'].includes(book.overrides?.[income.id+'@'+day]?.status))dates.add(day);}return [...dates].sort();}
export function financialGoalProgress(g,book,data,savings=[]){const debt=g.goalType==='debt',account=data.accounts.find(a=>a.id===g.debtId),utilization=debt?utilizationPercent(g,account):null,needsLimit=utilization!==null&&!(Number(account?.limit)>0),target=debt?debtGoalTarget(g,account):goalTarget(g,book),remaining=debt?(account&&!needsLimit?Math.max(0,account.balance-target):null):Math.max(0,target-g.saved),progressStart=debt&&account?Math.max(Number(g.startBalance)||0,Number(account.original)||0,Number(account.openingBalance)||0):Number(g.startBalance)||0,span=debt?Math.max(0,progressStart-target):target,completed=debt?(remaining===null?0:Math.max(0,progressStart-account.balance)):g.saved,percent=span>0?Math.min(100,Math.max(0,completed/span*100)):remaining===0?100:0,forecastEnd=data.plan?.forecast?.at(-1)?.date||data.asOf,beyondForecast=!!g.date&&g.date>forecastEnd,dates=g.date?[...new Set((data.nextPaychecks||[]).filter(p=>p.date>=data.asOf&&p.date<=g.date).map(p=>p.date))].sort():[],required=remaining!==null&&dates.length&&!beyondForecast?round(remaining/dates.length):null,plan=savings.find(p=>p.list==='goals'&&p.id===g.id),status=debt?(!account?'Account unavailable':needsLimit?'Add credit limit':remaining===0?'Reached':'Tracking debt'):remaining===0?'Reached':!data.ready?'Confirm budget':g.goalType==='emergency'&&target<=0?'Set essential costs':!g.date?'No deadline':g.date<data.asOf?'Past deadline':beyondForecast?'Beyond forecast':!dates.length?'No forecast payday before deadline':plan?.ready&&plan.ready<=g.date&&!plan.overallocated?'On track':'Behind';return {debt,account,target,utilization,remaining,progressStart,percent,dates,required,status,weekly:plan?.weekly||0,projected:plan?.projected||0,ready:plan?.ready||null};}
