import {periods,reviewQueue,filterTransactions,reportData,periodInsights,total,transactionStyle} from './tools-data.js';
import {cleanHistory,shift} from './analysis.js';
import {reviewWarningItems} from './workflow.js';

export function createToolsUI(c){
 const {esc,dollars,btn,iconBadge,uiIcon,input,select,check,shortDate}=c;
 let heatSelection='';
 const data=()=>c.data(), book=()=>data().book, summary=()=>data().summary;
 const route=()=>{const [path,query='']=c.hash().replace(/^#/,'').split('?');return {path,tab:path.split('/')[1],query:new URLSearchParams(query)};};
 const routeTo=(path,filters={})=>{const q=new URLSearchParams(Object.entries(filters).filter(([,v])=>v!==''&&v!=null));return path+(q.size?'?'+q:'');};
 const go=(path,filters)=>c.navigate(routeTo(path,filters));
 const empty=text=>'<p class="tools-empty">'+esc(text)+'</p>';
 const headingIcons={'Spending Watch':'watch','Recurring Merchant Watch':'refresh','Small-purchase Patterns':'small','Where Your Money Went':'plan','Annual Spending Heatmap':'annual','Milestones':'wins','Recorded Activity':'receipt','All Caught Up':'check'};
 const card=(title,body,action='')=>'<section class="tools-card"><div class="tools-card-head"><h2>'+(headingIcons[title]?iconBadge(headingIcons[title],'blue'):'')+title+'</h2>'+action+'</div>'+body+'</section>';
 const wrap=html=>'<div class="tools-workspace">'+html+'</div>';
 const tabs=(items,active)=>'<nav class="tools-tabs" aria-label="View">'+items.map(([id,label])=>btn(label,'navigate',id,'aria-current="'+(id===active?'page':'false')+'"',id===active?'tools-tab active':'tools-tab')).join('')+'</nav>';
 const money=(v,tone='blue',inflow=false,preserveTone=false)=>'<span class="amount-bubble tone-'+tone+(v<0&&!preserveTone?' amount-negative':'')+'">'+(inflow&&v>=0?'+':'')+dollars(v)+'</span>';
 const style=transactionStyle;
 const categoryIcon=name=>iconBadge(...style(name));
 const categoryName=t=>t.adjustment?'Balance Correction':t.toAccountId?'Transfer':(t.paymentId||t.recordType==='payment')?'Debt payment':t.category||'Other';
 const accountName=id=>book().accounts.find(a=>a.id===id)?.name||'Untracked Account';
 const months=()=>periods(book(),summary().asOf);
 const monthName=m=>m==='all'?'All Dates':new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(m+'-01T12:00:00Z'));
 const currentMonth=()=>{const selected=route().query.get('month');return months().includes(selected)?selected:summary().asOf.slice(0,7);};
 const dateRail=date=>'<time class="tools-date" datetime="'+esc(date)+'">'+esc(shortDate(date))+'</time>';
 const pill=(label,action,id='',extra='')=>btn(label,action,id,extra,'tools-pill');
 const trash=(action,id,label)=>btn(uiIcon('trash'),action,id,'aria-label="'+esc(label)+'" title="'+esc(label)+'"','tools-trash');
 const show=(title,body,handler=null)=>c.show(title,'<div class="tools-dialog-content">'+body+(!handler?'<p id="form-error" class="negative" role="alert"></p>':'')+'</div>',handler);
 const done=()=>'<div class="tools-dialog-footer">'+pill('Done','close')+'</div>';
 const control=(label,name,options,value)=>'<label class="tools-control">'+esc(label)+'<select data-tools-control="'+name+'">'+options.slice().sort((a,b)=>a[0]===''?-1:b[0]===''?1:String(a[1]).localeCompare(String(b[1]),'en',{sensitivity:'base',numeric:true})).map(([v,l])=>'<option value="'+esc(v)+'" '+(v===value?'selected':'')+'>'+esc(l)+'</option>').join('')+'</select></label>';
 function txFilters(){const q=route().query;return {month:q.get('month')||'all',account:q.get('account')||'',institution:q.get('institution')||'',category:q.get('category')||'',kind:q.get('kind')||'',q:q.get('q')||'',ids:q.get('ids')?.split(',')};}
 function canApplyDebt(t){return t.direction==='Outflow'&&!t.pending&&!t.excluded&&!t.adjustment&&!t.toAccountId&&!t.paymentId&&!t.bankMatchId&&!t.goalId&&book().accounts.some(a=>a.id===t.accountId&&a.kind==='cash')&&!book().payments.some(p=>p.transactionId===t.id);}
 function txRows(rows,editable=true){if(!rows.length)return empty('No transactions match this view.');return '<div class="tools-tx-table" role="table" aria-label="Transactions"><div class="tools-tx-head" role="row"><span>Date</span><span>Description / Account</span><span>Category</span><span>Amount</span><span>Actions</span></div>'+rows.map(t=>{const name=categoryName(t),[icon,tone]=style(name),linked=t.paymentId||book().payments.some(p=>p.transactionId===t.id),fixed=t.adjustment||t.toAccountId||linked;return '<div class="tools-tx-row" role="row">'+dateRail(t.date)+'<div><strong>'+esc(t.name)+'</strong><small>'+esc(accountName(t.accountId))+(t.toAccountId?' → '+esc(accountName(t.toAccountId)):'')+(linked?' · Matched payment':'')+(t.plaidTransactionId?' · Bank history':t.historical?' · History only':'')+(t.suggestedCategory?' · Suggested: '+esc(t.suggestedCategory):'')+'</small></div>'+(editable&&!fixed?btn(iconBadge(icon,tone)+'<span>'+esc(name)+'</span>','tools-category',t.id,'aria-label="Change category for '+esc(t.name)+'"','tools-category'): '<span class="tools-category">'+iconBadge(icon,tone)+esc(name)+'</span>')+money(t.direction==='Outflow'?-Math.abs(t.amount):Math.abs(t.amount),tone,t.direction==='Inflow',true)+'<div class="tools-row-actions">'+(editable&&canApplyDebt(t)?pill('Apply to Debt','tools-apply-debt',t.id,'title="Apply to Personal Debt" aria-label="Apply to a personal debt"'):'<span aria-hidden="true"></span>')+(editable&&!fixed?pill('Edit','tools-edit-transaction',t.id):pill('View','tools-view-transaction',t.id))+(editable&&!fixed?trash('tools-delete-transaction',t.id,'Delete '+t.name):'<span aria-hidden="true"></span>')+'</div></div>';}).join('')+'</div>';}
 function transactionList(){return txRows(filterTransactions(book(),txFilters()));}
 function queueSection(title,icon,tone,count,body,open=false){return '<details class="tools-queue" data-section-key="tools-review-'+({duplicates:'review',match:'payment',uncategorized:'warning',imported:'wallet'}[icon]||icon)+'" '+(open?'open':'')+'><summary>'+iconBadge(icon,tone)+'<strong>'+title+'</strong><span class="tools-count">'+count+'</span><span class="tools-chevron">⌄</span></summary><div class="tools-expanded">'+body+'</div></details>';}
 function reviewWarnings(){return reviewWarningItems(book()).map(item=>'<div class="tools-review-warning" role="status"><span>'+esc(item.pending.length+' · '+item.title)+'</span>'+btn(uiIcon('close'),'tools-dismiss-review',item.kind,'aria-label="Dismiss '+esc(item.title)+' warning" title="Dismiss warning"','tools-trash')+'</div>').join('');}
 const compareTile=(label,name,date,amount,icon,tone,detail='')=>'<div class="tools-compare-tile"><small class="tools-record-label">'+esc(label)+'</small><div>'+iconBadge(icon,tone)+'<span><strong>'+esc(name)+'</strong><small>'+shortDate(date)+(detail?' · '+esc(detail):'')+'</small></span>'+money(amount,tone)+'</div></div>';
 function queue(){const b=book(),r=reviewQueue(b);if(!r.count)return card('All Caught Up',empty('No transactions need review.'));return (r.duplicates.length?queueSection('Compare possible duplicates','duplicates','blue',r.duplicates.length,r.duplicates.map(g=>'<div class="tools-comparison">'+g.items.slice(0,2).map((t,i)=>compareTile('Record '+String.fromCharCode(65+i),t.name,t.date,t.amount,...style(categoryName(t)),accountName(t.accountId))).join('')+pill('Compare Records','tools-duplicates',g.key)+'</div>').join(''),true):'')+(r.matches.length?queueSection('Review debt payment matches','match','blue',r.matches.length,r.matches.map(m=>'<div class="tools-comparison">'+compareTile('Recorded Payment',m.payment.debtName,m.payment.date,m.payment.amount,'payment','indigo')+compareTile('Possible Cash Match',m.candidates[0].name,m.candidates[0].date,m.candidates[0].amount,'wallet','mint',accountName(m.candidates[0].accountId))+pill('Review Match','tools-match',m.payment.id)+'</div><p class="tools-note">Review before linking; cash should be deducted once.</p>').join(''),true):'')+(r.uncategorized.length?queueSection('Categorize transactions','uncategorized','gray',r.uncategorized.length,txRows(r.uncategorized),route().query.get('focus')==='other'):'')+(r.history?queueSection('Review imported history','imported','teal',r.history,'<p>Review imported records before including them in reports. Possible matches to existing spending or payments are held here: discard an import if it is already recorded. They do not change current balances.</p>'+pill('Review Imported History','tools-imports')):'');}
  function transactions(){
  const r=reviewQueue(book()),review=route().tab==='review';
  const tabList=[['transactions/all','All Transactions'],['transactions/review','Needs Review'+(r.count?' <span class="tools-count">'+r.count+'</span>':'')]];
  const current=review?'transactions/review':'transactions/all';
  return wrap('<div class="tools-toolbar">'+tabs(tabList,current)+pill(uiIcon('spend')+' Record Transaction','tools-new-transaction')+'</div>'+(review?'<p>Items stay here until reviewed. Nothing is matched or deleted automatically.</p>'+reviewWarnings()+queue(): '<div class="tools-filters"><label class="tools-search">'+uiIcon('search')+'<input id="tools-tx-search" value="'+esc(txFilters().q)+'" placeholder="Search transactions" aria-label="Search transactions"></label>'+control('Dates','transactionMonth',[['all','All Dates'],...months().map(m=>[m,monthName(m)])],txFilters().month)+pill('Filters','tools-filters')+pill('Clear Filters','tools-clear-filters')+'</div>'+card('Recorded Activity','<div id="tools-tx-list">'+transactionList()+'</div>')+'<p class="tools-note">Matched payments count once. Transfers and balance corrections stay separate from spending reports.</p>'));}
 function nav(){const count=reviewQueue(book()).count;return [['transactions/all','receipt','Transactions'],['recurring','calendar','Recurring'],['insights','intelligence','Insights'],['reports/monthly','annual','Reports']].map(([id,icon,label])=>btn('<span class="ico">'+uiIcon(icon)+'</span>'+label+(label==='Transactions'&&count?' <span class="tools-nav-count">'+count+'</span>':''),'navigate',id,'aria-current="'+(c.page()===id.split('/')[0]?'page':'false')+'"')).join('');}
 const plainRows=rows=>rows.length?rows.map(t=>'<div class="tools-readonly-row">'+categoryIcon(categoryName(t))+'<div><strong>'+esc(t.name)+'</strong><small>'+shortDate(t.date)+(t.accountId?' · '+esc(accountName(t.accountId)):'')+'</small></div>'+money(t.direction==='Outflow'?-Math.abs(t.amount):Math.abs(t.amount),style(categoryName(t))[1],t.direction==='Inflow')+'</div>').join(''):empty('No recorded activity in this period.');
 const metric=(label,value,icon,tone,action='',id='')=>{const tag=action?'button':'div';return '<'+tag+' class="tools-metric gradient-'+tone+'"'+(action?' data-action="'+action+'" data-id="'+esc(id)+'"':'')+'>'+iconBadge(icon,tone)+'<span><small>'+label+'</small><strong>'+value+'</strong></span></'+tag+'>';};
 const fold=(title,body,key)=>'<details class="tools-fold" data-section-key="'+esc(key)+'"><summary>'+title+'<span class="tools-chevron">⌄</span></summary><div class="tools-expanded">'+body+'</div></details>';
 const drill=(rows,label='View Transactions')=>pill(label,'tools-source',JSON.stringify(rows.map(t=>t.id)));
 
 function insightOptions(item){return '<details class="tools-options"><summary aria-label="Insight options">•••</summary><div>'+pill('Snooze 7 Days','tools-snooze',item.id)+pill('Dismiss Insight','tools-dismiss',item.id)+'</div></details>';}
 function insightBlock(item,view){const d=item.data;let title,body;
  if(item.kind==='category'){title=categoryIcon(item.name)+'<strong>'+esc(item.name)+'</strong>'+money(d.current,style(item.name)[1])+'<span class="tools-pace-track"><span style="width:'+Math.min(100,Math.max(0,d.current/Math.max(1,d.projected)*100))+'%"></span></span><span class="tools-forecast-value">'+dollars(d.projected)+'</span><small class="tools-usual-range">'+(d.average?dollars(d.low)+' – '+dollars(d.high):'Not enough history')+'</small>';const recent=Array.from({length:4},(_,i)=>{const dt=new Date(view.month+'-01T12:00:00Z');dt.setUTCMonth(dt.getUTCMonth()-3+i);const month=dt.toISOString().slice(0,7),rows=view.rows.filter(t=>t.date.startsWith(month)&&(t.category||'Other')===item.name);return {month,amount:total(rows)};});const max=Math.max(1,...recent.map(x=>x.amount));body='<p>Usual range: '+(d.average?dollars(d.low)+' – '+dollars(d.high):'Not enough history')+' · '+d.historyMonths+'/3 previous months observed.</p><div class="tools-trend-bars" aria-label="Recorded monthly spending">'+recent.map(p=>'<div><strong>'+dollars(p.amount)+'</strong><span class="tools-trend-column" style="height:'+Math.max(3,p.amount/max*90)+'px"></span><small>'+esc(monthName(p.month))+'</small></div>').join('')+'</div><p class="tools-note">Month pace is a straight-line projection, not a bill. Missing history and one-time costs affect the comparison.</p>'+drill(view.rows.filter(t=>t.date.startsWith(view.month)&&(t.category||'Other')===item.name));}
  else{title=iconBadge(item.kind==='small'?'small':'merchant',item.kind==='small'?'gold':'peach')+'<strong>'+esc(item.name)+'</strong>'+money(item.kind==='small'?d.total:d.latest,item.kind==='small'?'gold':'peach')+'<small>'+esc(item.kind==='small'?d.count+' purchases in 30 days':d.signal)+'</small>';const rows=view.rows.filter(t=>d.ids.includes(t.id));body=plainRows(rows)+(item.kind==='small'?'<p class="tools-note">A pattern to notice, not automatically a problem.</p>':'<p>Typical charge '+dollars(d.typical)+' · Next expected around '+shortDate(d.next)+'. Confirm a change before editing Calendar.</p>')+drill(rows);if(item.kind==='merchant'){const bill=book().bills.find(b=>b.name.trim().toLowerCase()===item.name.trim().toLowerCase());if(bill)body+=pill('Edit Related Bill','tools-edit-bill',bill.id);}}
  return fold('<span class="tools-insight-summary '+(item.kind==='category'?'tools-pace-summary':'')+'">'+title+'</span>',body+insightOptions(item),item.id);
 }
 function insights(){const view=periodInsights(book(),summary(),currentMonth()),categories=view.visible.filter(x=>x.kind==='category'),merchants=view.visible.filter(x=>x.kind==='merchant'),small=view.visible.filter(x=>x.kind==='small'),grocery=view.categories.find(x=>/grocery|food/i.test(x.category)),rising=view.recurring.filter(x=>x.signal==='Price increase').length,smallSum=total(view.leaks.map(x=>({amount:x.total})));return wrap('<div class="tools-toolbar"><p>Understand what is changing in your spending.</p>'+control('Period','insightMonth',months().map(m=>[m,monthName(m)]),view.month)+'</div><div class="tools-metrics">'+metric('Grocery / Food Pace',grocery?dollars(grocery.projected):'—','grocery','grocery')+metric('Recurring Price Changes',String(rising),'merchant','peach')+metric('Small Purchases',dollars(smallSum),'small','gold')+'</div><div class="tools-insights-grid">'+card('Spending Watch','<p class="tools-section-description">Track spending against forecasts and usual ranges.</p><div class="tools-pace-head"><span>Category</span><span>So far</span><span>Forecast</span><span>Usual range</span></div>'+(categories.map(i=>insightBlock(i,view)).join('')||empty('No visible category patterns for this month.')))+'<div>'+card('Recurring Merchant Watch',merchants.map(i=>insightBlock(i,view)).join('')||empty('Patterns need at least three recorded dates.'))+card('Small-purchase Patterns',small.map(i=>insightBlock(i,view)).join('')||empty('No repeated small-purchase patterns.'))+'</div></div>'+fold('Hidden & Snoozed Insights',Object.entries(book().insightStates||{}).map(([id,state])=>{const item=view.cards.find(x=>x.id===id);return '<div class="tools-review-row"><div><strong>'+esc(item?.name||id.split(':').slice(1,-1).join(':')||'Insight')+'</strong><small>'+esc(state.status)+(state.until?' until '+shortDate(state.until):'')+'</small></div>'+pill('Restore','tools-restore-insight',id)+'</div>';}).join('')||empty('Nothing hidden.'),'hidden-insights')+'<p class="tools-note">Suggestions are based on reviewed records. Snoozing or dismissing a suggestion does not complete required Home tasks.'+(view.withheld?' '+view.withheld+' suspected duplicate records are withheld from analysis.':'')+'</p>');}
 function reportPeriod(tab){if(tab==='monthly')return currentMonth();const years=[...new Set(months().map(m=>m.slice(0,4)))],y=route().query.get('year');return years.includes(y)?y:summary().asOf.slice(0,4);}
 function reportMetrics(r){return '<div class="tools-metrics">'+metric('Recorded Income',dollars(r.income),'income','mint','tools-report-total','income')+metric('Spending',dollars(r.spending),'spending','rose','tools-report-total','spending')+metric('Debt Payments',dollars(r.payments),'payment','indigo','tools-report-total','payments')+'</div><p class="tools-note">Recorded activity only. Transfers and balance corrections excluded.'+(r.withheld?' '+r.withheld+' suspected duplicate records withheld across history.':'')+'</p>';}
 function heatmap(r){if(!r.heatmap.length)return empty('Categorize transactions to build the annual heatmap.');const current=summary().asOf.slice(0,7),names=Array.from({length:12},(_,i)=>new Intl.DateTimeFormat('en-US',{month:'short',timeZone:'UTC'}).format(new Date(Date.UTC(2026,i,1))));let selected=null;const html='<div class="tools-heatmap" role="table" aria-label="Annual Spending Heatmap"><div class="tools-heat-row tools-heat-head" role="row"><span>Category</span>'+names.map(n=>'<span>'+n+'</span>').join('')+'</div>'+r.heatmap.map((cat,i)=>'<div class="tools-heat-row" role="row"><span>'+categoryIcon(cat.name)+esc(cat.name)+'</span>'+cat.months.map((value,j)=>{const month=r.period+'-'+String(j+1).padStart(2,'0'),key=JSON.stringify([r.period,cat.name,month]),level=value===0?0:Math.max(1,Math.ceil(value/Math.max(...cat.months)*4));if(heatSelection===key)selected={cat,month};return month>current?'<span class="tools-future" aria-label="'+names[j]+' has not occurred">—</span>':btn('<span class="tools-sr-only">'+dollars(value)+'</span>','tools-heat',key,'title="'+esc(cat.name+' · '+monthName(month)+' · '+dollars(value))+'" aria-label="'+esc(cat.name+' · '+monthName(month)+' · '+dollars(value))+'" aria-pressed="'+(heatSelection===key)+'"','tools-heat-cell heat-'+level);}).join('')+'</div>').join('')+'</div><p class="tools-note">Lighter → darker means lower → higher spending within each category. Select a cell to see its records.</p>';return html+(selected?'<section class="tools-heat-detail"><div class="tools-card-head"><h3>'+esc(selected.cat.name)+' · '+monthName(selected.month)+'</h3>'+money(total(selected.cat.rows.filter(t=>t.date.startsWith(selected.month))),style(selected.cat.name)[1])+'</div>'+plainRows(selected.cat.rows.filter(t=>t.date.startsWith(selected.month)))+'<div class="tools-dialog-footer">'+drill(selected.cat.rows.filter(t=>t.date.startsWith(selected.month)))+pill('Close Breakdown','tools-close-heat')+'</div></section>':'');}
 function progress(year){const milestones=(summary().milestones||[]).filter(m=>m.date.startsWith(year)).slice().sort((a,b)=>b.date.localeCompare(a.date));return card('Milestones',milestones.map(m=>{let action='';if(m.id.startsWith('debt:'))action=pill('View Debt','navigate','debt');if(m.id.startsWith('target:'))action=pill('View Goals','navigate','goals');if(m.id==='buffer')action=pill('View Plan','navigate','plan');return '<div class="tools-milestone">'+dateRail(m.date)+iconBadge('wins','lav')+'<div><strong>'+esc(m.title)+'</strong><small>Observed in your recorded budget</small>'+fold('Details','<p>Observed on '+shortDate(m.date)+'. This milestone records progress and creates no new transfer or payment.</p>'+action,'milestone-'+m.id)+'</div></div>';}).join('')||empty('Milestones appear as recorded progress is observed.'))+'<p class="tools-note">Progress shows milestones only.</p>';}
 function reports(forceTab=''){const tab=forceTab||(['monthly','annual','progress'].includes(route().tab)?route().tab:'monthly'),period=reportPeriod(tab);return wrap('<div class="tools-toolbar">'+tabs([['reports/monthly','Monthly'],['reports/annual','Annual'],['reports/progress','Progress']],'reports/'+tab)+(tab==='monthly'?control('Month','reportMonth',months().map(m=>[m,monthName(m)]),period):control('Year','reportYear',[...new Set(months().map(m=>m.slice(0,4)))].map(y=>[y,y]),period))+'</div>'+(tab==='progress'?progress(period):(()=>{const r=reportData(book(),summary(),period);return reportMetrics(r)+(tab==='annual'?card('Annual Spending Heatmap',heatmap(r)):card('Where Your Money Went',r.categories.map(cat=>fold('<span class="tools-report-category">'+categoryIcon(cat.name)+'<strong>'+esc(cat.name)+'</strong><span class="tools-spending-track"><span style="width:'+Math.max(0,cat.amount/Math.max(1,...r.categories.map(x=>x.amount))*100)+'%"></span></span>'+money(cat.amount,'blue')+'</span>',plainRows(cat.rows)+drill(cat.rows),'report-'+period+'-'+cat.name)).join('')||empty('No recorded spending this month.')))+'<button class="tools-net gradient-mint" data-action="tools-report-total" data-id="net">'+iconBadge('up','mint')+'<strong>Recorded Net Cash Flow</strong>'+money(r.net,r.net<0?'red':'mint',true)+'<span>See the cash calculation</span></button>';})())+'<p class="tools-note">Report email preferences are in '+btn('Settings','navigate','settings/reports')+'.</p>');}
 function reportPopup(kind){const tab=route().tab==='annual'?'annual':'monthly',r=reportData(book(),summary(),reportPeriod(tab));if(kind==='net')return show('Net Cash Flow', '<p>'+esc(r.period)+'</p><div class="tools-review-row">Cash inflows '+money(r.cashIncome,'mint',true)+'</div><div class="tools-review-row">Cash spending '+money(-r.cashSpending,'rose')+'</div><div class="tools-review-row">Cash debt payments '+money(-r.cashPayments,'indigo')+'</div><div class="tools-review-row"><strong>Net Cash Flow</strong>'+money(r.net,r.net<0?'red':'mint',true)+'</div><p>Transfers and corrections are excluded. Card purchases affect cash when paid. Non-income cash inflows such as refunds are included here.</p>'+done());const rows=kind==='income'?r.incomeRows:kind==='spending'?r.spendingRows:r.paymentRows;show(({income:'Recorded Income',spending:'Spending Breakdown',payments:'Debt Payments'})[kind],'<p>'+esc(r.period)+'</p>'+(kind==='spending'?r.categories.map(cat=>'<div class="tools-readonly-row">'+categoryIcon(cat.name)+'<span>'+esc(cat.name)+'</span>'+money(cat.amount,'rose')+'</div>').join(''):plainRows(rows))+'<div class="tools-review-row"><strong>Total</strong>'+money(r[kind],kind==='income'?'mint':kind==='spending'?'rose':'indigo',kind==='income')+'</div><p>Matched payments count once.</p>'+(kind==='payments'?pill('View Recorded Payments','navigate','debt'):drill(rows))+done());}
 async function action(action,id){const b=book();
  if(action==='tools-dismiss-review'){await c.write('dismissReviewWarning',{kind:id});return true;}
  if(action==='tools-apply-debt'){c.applyPersonalDebt(id);return true;}
  if(action==='tools-new-transaction'){c.spendingForm();return true;}
  if(action==='tools-edit-transaction'){c.editTransaction(id);return true;}
  if(action==='tools-view-transaction'){const t=b.transactions.find(t=>t.id===id);if(!t)throw Error('Reload to find this record.');const p=b.payments.find(p=>p.transactionId===id);show('Transaction Details',plainRows([t])+(p?'<p>Linked to '+esc(p.debtName)+'. Cash is counted once; principal '+dollars(p.principal)+'.</p>'+pill('View Recorded Payments','navigate','debt'):t.adjustment?'<p>This is a balance correction, excluded from spending reports.</p>'+pill('Manage Account','navigate','settings/accounts'):t.toAccountId?'<p>Transfer to '+esc(accountName(t.toAccountId))+'. It is excluded from spending.</p>'+pill('Edit Transfer','tools-edit-transaction',id)+trash('tools-delete-transaction',id,'Delete Transfer'):'')+done());return true;}
  if(action==='tools-delete-transaction'){const t=b.transactions.find(t=>t.id===id);if(!t)throw Error('Record no longer exists.');show('Delete Transaction?',plainRows([t])+'<p>This removes the record and reverses its effect on the balance. You can undo this change.</p>',()=>c.write('remove',{list:'transactions',id}));return true;}
  if(action==='tools-category'){const t=b.transactions.find(t=>t.id===id);show('Choose Category','<fieldset class="tools-category-choices"><legend>Choose a category</legend>'+[...new Set([t.category||'Other',...c.categories])].map(name=>'<label>'+categoryIcon(name)+'<span>'+esc(name)+'</span><input type="radio" name="category" value="'+esc(name)+'" '+(name===(t.category||'Other')?'checked':'')+' required></label>').join('')+'</fieldset>',d=>c.write('category',{id,category:d.category}));return true;}
  if(action==='tools-filters'){const f=txFilters();show('Filter Transactions',select('Account','account',[['','All Accounts'],...b.accounts.map(a=>[a.id,a.name])],f.account)+select('Category','category',[['','All Categories'],...[...new Set([...c.categories,...b.transactions.map(t=>t.category||'Other')])].sort().map(x=>[x,x])],f.category)+select('Type','kind',[['','All Transactions'],['balance','Balance Updates']],f.kind)+select('Dates','month',[['all','All Dates'],...months().map(m=>[m,monthName(m)])],f.month),d=>{c.close();go('transactions/all',{...f,...d,institution:''});});return true;}
  if(action==='tools-clear-filters'){go('transactions/all');return true;}
  if(action==='tools-duplicates'){const g=reviewQueue(b).duplicates.find(g=>g.key===id);if(!g)throw Error('This group has already been reviewed.');show('Compare Possible Duplicates','<p>Similar descriptions and amounts may be separate purchases. Select the specific record to remove, or keep both.</p>'+g.items.map((t,i)=>'<section class="tools-compare-record">'+compareTile('Record '+(i+1),t.name,t.date,t.amount,...style(categoryName(t)),accountName(t.accountId))+pill('Remove This Record','tools-delete-transaction',t.id)+'</section>').join('')+pill('Keep All as Separate Purchases','tools-keep-duplicates',id)+done());return true;}
  if(action==='tools-keep-duplicates'){await c.write('dismissDuplicate',{key:id});return true;}
  if(action==='tools-match'){const m=reviewQueue(b).matches.find(m=>m.payment.id===id);if(!m)throw Error('Match no longer available.');show('Match Recorded Payment','<div class="tools-match-pair">'+compareTile('Recorded Payment',m.payment.debtName,m.payment.date,m.payment.amount,'payment','indigo')+compareTile('Possible Cash Match',m.candidates[0].name,m.candidates[0].date,m.candidates[0].amount,'wallet','mint',accountName(m.candidates[0].accountId))+'</div>'+select('Choose the Cash Expense','transactionId',[['','Choose a record'],...m.candidates.map(t=>[t.id,shortDate(t.date)+' · '+t.name+' · '+dollars(t.amount)])],'')+'<p>The cash expense is kept. The payment’s extra cash deduction is removed. Principal is not reduced again. You can Undo the match.</p>',d=>c.write('matchPayment',{id,transactionId:d.transactionId}));return true;}
  if(action==='tools-imports'){show('Review Imported Records','<p>History only: these records do not change current balances. Check pending items and transfers before accepting.</p>'+b.reviewTransactions.map(t=>'<label class="tools-import-row"><input type="checkbox" data-tools-import="'+esc(t.id)+'"><span>'+esc(t.name)+'<small>'+shortDate(t.date)+(t.pending?' · Pending':'')+'</small></span>'+money(t.direction==='Outflow'?-Math.abs(t.amount):Math.abs(t.amount),'teal',t.direction==='Inflow')+'</label>').join('')+'<div class="tools-dialog-footer">'+pill('Discard Checked','tools-discard-imports')+pill('Accept Checked','tools-accept-imports')+'</div>');return true;}
  if(['tools-accept-imports','tools-discard-imports'].includes(action)){const ids=c.checkedImports();if(!ids.length)throw Error('Select at least one record.');await c.write('reviewHistory',{ids,accept:action==='tools-accept-imports'});return true;}
  if(action==='tools-source'){const ids=JSON.parse(id);go('transactions/all',{month:'all',ids:ids.join(',')||'__none__'});return true;}
  if(action==='tools-edit-bill'){c.billForm(id);return true;}
  if(['tools-snooze','tools-dismiss','tools-restore-insight'].includes(action)){await c.write('insightState',{id,status:action==='tools-snooze'?'snoozed':action==='tools-dismiss'?'dismissed':'reset',until:shift(summary().asOf,7)});return true;}
  if(action==='tools-report-total'){reportPopup(id);return true;}
  if(action==='tools-heat'){heatSelection=id;await c.render();c.$('.tools-heat-detail')?.scrollIntoView?.({block:'nearest'});return true;}
  if(action==='tools-close-heat'){heatSelection='';await c.render();return true;}
  return false;
 }
 function change(name,value){if(name==='transactionMonth')go('transactions/all',{...txFilters(),month:value,ids:txFilters().ids?.join(',')});if(name==='insightMonth')go('insights',{month:value});if(name==='reportMonth')go('reports/monthly',{month:value});if(name==='reportYear')go('reports/'+(route().tab==='progress'?'progress':'annual'),{year:value});}
 function search(q){const f={...txFilters(),q,ids:txFilters().ids?.join(',')};c.replaceHash(routeTo('transactions/all',f));const target=c.$('#tools-tx-list');if(target)target.innerHTML=transactionList();}
 return {transactions,insights,reports,nav,action,change,search,reportPopup,transactionList};
}
