// Optional private SMTP submission. TLS is required before credentials are sent.
import {connect} from 'node:tls';
import {randomUUID} from 'node:crypto';
import {monthlyReport} from '../analysis.js';
export function yearlyReport(book,data,year){const reports=Array.from({length:12},(_,i)=>monthlyReport(book,data,year+'-'+String(i+1).padStart(2,'0'))),total={month:String(year),periodType:'yearly',income:0,spending:0,payments:0,net:0,recordCount:0,withheld:0};for(const r of reports){for(const k of ['income','spending','payments','net','recordCount'])total[k]=Math.round((total[k]+(r[k]||0))*100)/100;total.withheld=Math.max(total.withheld,r.withheld||0);}return total;}
export async function deliverYearlyReview(store,book,data,config,send=sendReview){if(book.sampleMode)return 'Disabled in sample mode';if(!book.settings.reviewEmail?.yearly)return 'Off';if(!config)return 'Private SMTP setup needed';const year=Number(data.asOf.slice(0,4))-1,key='mail-year-'+year,prior=await store.get(key);if(prior)return year+': '+prior.status;const report=yearlyReport(book,data,year);if(!report.recordCount&&!report.payments)return 'No records for '+year;await store.put(key,{status:'Attempt started; delivery not yet confirmed',at:new Date().toISOString()});try{await send(config,book.settings.reviewEmail.email,report);await store.put(key,{status:'Accepted by mail server',at:new Date().toISOString()});return year+': Accepted by mail server';}catch{await store.put(key,{status:'Failed or uncertain — no automatic retry',at:new Date().toISOString()});return year+': Failed or uncertain — no automatic retry';}}
export function validateMail(c){if(!c||!/^([a-z0-9-]+\.)+[a-z0-9-]+$/i.test(c.host||''))throw Error('Enter a valid SMTP hostname.');for(const k of ['from','to'])if(c[k]&&!/^[a-z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-z0-9.-]+\.[a-z]{2,}$/i.test(c[k]))throw Error('Enter a valid email address.');if(!c.from||!c.user||!c.password||/[\r\n\0]/.test(c.user+c.password))throw Error('Enter valid private SMTP credentials.');return c;}
export function reviewMessage(report){if(report.testOnly)return 'This is a Budget HQ test email. Your email connection is working. No budget information is included.';const money=n=>Number(n).toFixed(2);return `Budget HQ review: ${report.month}\n\nRecorded income: $${money(report.income)}\nRecorded spending: $${money(report.spending)}\nDebt payments: $${money(report.payments)}\nNet cash flow: $${money(report.net)}\n\nBased on reviewed local records. Transfers and balance corrections are excluded. Linked payments count once. ${report.withheld} suspected duplicate records withheld across history. This may be incomplete if records are missing.\nOpen Budget HQ for details.`;}
export async function sendReview(config,to,report,connectSocket=connect){const c=validateMail({...config,to});const socket=connectSocket({host:c.host,port:465,servername:c.host,minVersion:'TLSv1.2',rejectUnauthorized:true});let buffer='',lines=[],queue=[],waiting=null,failure=null;const fail=()=>{failure=Error('SMTP connection failed or timed out. Check private mail setup.');if(waiting){waiting.reject(failure);waiting=null;}socket.destroy();};socket.setTimeout(20000,fail);socket.on('error',fail);socket.on('close',()=>{if(waiting)fail();});socket.on('data',chunk=>{buffer+=chunk.toString();if(buffer.length>65536)return fail();let i;while((i=buffer.indexOf('\r\n'))>=0){const line=buffer.slice(0,i);buffer=buffer.slice(i+2);if(!/^\d{3}[ -]/.test(line))return fail();lines.push(line);if(line[3]===' '){const response={code:Number(line.slice(0,3)),lines};lines=[];if(waiting){waiting.resolve(response);waiting=null;}else queue.push(response);}}});
 const reply=()=>failure?Promise.reject(failure):queue.length?Promise.resolve(queue.shift()):new Promise((resolve,reject)=>{waiting={resolve,reject};});const expect=async(codes)=>{const r=await reply();if(!codes.includes(r.code))throw Error('SMTP rejected the review (code '+r.code+'). Check account setup and recipient.');return r;};const command=async(text,codes)=>{socket.write(text+'\r\n');return expect(codes);};
 try{await expect([220]);const hello=await command('EHLO budget-hq.local',[250]);if(!hello.lines.some(l=>/AUTH.*\bPLAIN\b/i.test(l)))throw Error('SMTP server must support AUTH PLAIN over TLS.');await command('AUTH PLAIN '+Buffer.from('\0'+c.user+'\0'+c.password).toString('base64'),[235]);await command('MAIL FROM:<'+c.from+'>',[250]);await command('RCPT TO:<'+to+'>',[250,251]);await command('DATA',[354]);const body=Buffer.from(reviewMessage(report)).toString('base64').match(/.{1,76}/g).join('\r\n');await command(`From: <${c.from}>\r\nTo: <${to}>\r\nSubject: ${report.testOnly?'Budget HQ test email':'Budget HQ '+(report.periodType==='yearly'?'yearly':'monthly')+' review '+report.month}\r\nDate: ${new Date().toUTCString()}\r\nMessage-ID: <${randomUUID()}@budget-hq.local>\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Transfer-Encoding: base64\r\n\r\n${body}\r\n.`,[250]);socket.end('QUIT\r\n');return true;}finally{socket.destroy();}
}
export async function sendTestMail(config,to,connectSocket=connect){return sendReview(config,to,{testOnly:true},connectSocket);}
export async function deliverMonthlyReview(store,book,summary,config,send=sendReview){if(book.sampleMode)return 'Disabled in sample mode';if(!book.settings.reviewEmail?.enabled)return 'Off';if(!config)return 'Private SMTP setup needed';const d=new Date(summary.asOf+'T12:00:00Z');d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()-1);const month=d.toISOString().slice(0,7),key='mail-'+month,prior=await store.get(key);if(prior)return month+': '+prior.status;const report=monthlyReport(book,summary,month);if(!report.recordCount&&!report.payments)return 'No records for '+month;await store.put(key,{status:'Attempt started; delivery not yet confirmed',at:new Date().toISOString()});try{await send(config,book.settings.reviewEmail.email,report);await store.put(key,{status:'Accepted by mail server',at:new Date().toISOString()});return month+': Accepted by mail server';}catch(e){await store.put(key,{status:'Failed or uncertain — no automatic retry',at:new Date().toISOString()});return month+': Failed or uncertain — check mail setup; no automatic retry';}}
